### ISSUE TITLE
Old review appears after new review submitted

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1015]
This issue was reported by Guiyang Fan, gfan:

> I've encountered a weird problem when submitting reviews. I submitted my updated review but somehow my old review appeared in the appended list of updated reviews, and luckily i am able to go back on my browser and resubmitted it again. 

This would be for Program 2 in CSC/ECE 517, Fall 2017.

**Comment by Winbobob** [comment]
I cannot reproduce this issue.
