### ISSUE TITLE
Cleaning the migration files

### ISSUE THREAD

**Issue by ferryxo** [expertiza/expertiza#1019]
I and Neha tried to run rake db:migrate on a clean slate database. It doesn't work since there all a lot of migration files that need classes, which have been deleted during refactoring (but apparently, they forgot to remove the corresponding migration files too).

one could run rake db:migrate and check the classes that are missing, and whether those migration files are still relevant. we do need a snapshot of the working DB schema, before someone poke around with these migration files. 

example:
uninitialized constant CreateLeaderboards::Leaderboard
/Users/ferry/Downloads/ExpertizaCode/tagging_comment_new_fork/expertiza/db/migrate/128_create_leaderboards.rb:9:in `up'
NameError: uninitialized constant CreateLeaderboards::Leaderboard

**Comment by Winbobob** [comment]
I don't think it is a good idea to remove the migration files. Yes, some old migration does not work. But we may refer to them when changing DB. If you import the scrubbed DB, migrations should succeed.
