### ISSUE TITLE
Reviewer told that work had NOT been submitted when it really had been submitted

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1029]
This suspicious situation was just noted.  On the Madeup Problem assignment in 506, kkpaul was assigned to review the team including asfadnav, and the interface told him that asfadnav had not submitted his work yet.  But he actually _had_ submitted his work, and indeed, on his dashboard it said the problem was "Finished."  In fact, he had selected a topic from Chapter 4, and Chapter 4 reviews aren't finished yet.

So something is going on here, perhaps only affecting staggered-deadline assignments.

KENNY PAUL | KENNY PAUL | 1:38 PM (1 hour ago) |   |  
Hello Prof. Gehringer,

I am trying to do a review for the made-up problem. But I am unable to add a topic to review. It is showing"Note: You can't have more than 2 outstanding reviews. You must complete one of your outstanding reviews before selecting another. "
I have done one review for the topic on "Assigning tasks to threads"
The second review somehow got allocated to me on the last day of 2nd feedback for made up problem cycle 2, thus was not able to complete it on time. Can you please reset my second review so that i can select from the list for the made-up problem cycle 3.

I have spoken with TA and they told only the professor can do the needful.
My unity id: kkpaul

Thanks and regards,
Kenny Paul

Ed Gehringer <efg@ncsu.edu> | Ed Gehringer <efg@ncsu.edu> | 2:35 PM (11 minutes ago) |   |  
Ed Gehringer <efg@ncsu.edu>
to KENNY | to KENNY
Hi Kenny,

I deleted the review, and you can now select a new one.  I don't know how this happened, because the student in question had submitted a problem.  The review period on it might have expired, but I doubt it, because only the first set of reviews had been completed, and they didn't include Ch. 4.

Cheers,
[Dr.] Ed Gehringer

**Comment by Saurabh110** [comment]
Could not reproduce.
