### ISSUE TITLE
StudentTaskController error on logging in or impersonating

### ISSUE THREAD

**Issue by Suvodeep90** [expertiza/expertiza#1034]
With certain students, when they are trying to access their account or when an admin is trying to impersonate that student it shows some error saying hyperlinks method not defined.
Student ID: student20
password:password

Admin:super_administrator2
password:password
Please check the screen shot for more details.
![issue with student impresonating](https://user-images.githubusercontent.com/31140098/31974195-1bba2c9a-b8f8-11e7-82f6-a28a92c83bea.JPG)

**Comment by Winbobob** [comment]
You could try to impersonate students will larger ids, link 5473.

**Comment by nikolaygtitov** [comment]
The issue is irreproducible based on the latest 'beta' branch. I can access student20 account and I can impersonate his account from super_administartor2 account. See the following:

![image](https://user-images.githubusercontent.com/8548602/62901591-327ff200-bd2b-11e9-8ae6-604046b6e33a.png)

**Comment by efg** [comment]
Indeed, we were able to impersonate this student and it worked normally.
