### ISSUE TITLE
Refactor signup_sheet_controller [rename it to that]

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#104]
sign_up_sheet_controller.rb has lots of functionality that belongs in different controllers, such as  generate_team_name.  This functionality should be moved to other controllers.  Ultimately, the size of signup_sheet_controller should be about 1/3 of the present, or about 225 lines.

The name should be changed from "sign_up" to "signup", because "signup" in this usage is an adjective, not a verb.  Projects that involve refactoring would be well advised to use RubyMine instead of RadRails.

Includes issues #91 and #92, which are needed bug fixes in signup-sheet functionality.

**Comment by yangsong8** [comment]
We have renamed it to sign_up_sheet_controller.rb

**Comment by efg** [comment]
The renaming should still be done, but most of this functionality has already been added.
