### ISSUE TITLE
Refactor deadline types

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#107]
Expertiza deadlines have a variety of types, e.g., signup, drop-topic, submission, review, metareview.  There are also resubmission & rereview deadline types, which apply to all rounds of review except the first.  This has been an unnecessary complication.  It will further complicate the code when new deadline types are added, because we want to have a separate right for each kind of deadline type, and the resubmission & rereview deadlines make the set of deadline types inconveniently large.
Remove resubmission & rereview deadline types, and add the new deadline types that are needed.

This is grouped with #21 as a 517 project candidate

**Comment by efg** [comment]
This may have been completely fixed by now.  Are there still vestiges of Resubmission and Rereview deadlines?

**Comment by yangsong8** [comment]
Sir, resubmission and rereview deadline (and deadline rights) have been removed from current code. I think we can close this issue now.

**Comment by efg** [comment]
If this means that there are no occurrences of "resubmission",
"Resubmission", "re-submission", "Re-submission", "rereview", "Rereview",
"re-review", "Re-review" in either the code or db schema, then yes, the
issue can be closed.

Thanks,
Ed

**Comment by yangsong8** [comment]
Correct sir, those terms should be all removed.
