### ISSUE TITLE
Instructor can't participate in an assignment

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1072]
During the TLT Group "designated learner" session on 26 Oct 2017.  we found that an instructor could not also be a participant in an assignment.  An instructor who tried to click on an assignment in the task list got a message saying that a eula action is not permitted for an instructor.

**Comment by Rui5** [comment]
Cannot reproduce this issue. I think fixing issue #1064 will help with this issue.

**Comment by ZachariahMathews** [comment]
Fixed by pull request #1323
