### ISSUE TITLE
Export enhancement for AssignmentParticipants and CourseParticipants

### ISSUE THREAD

**Issue by arjunssharma** [expertiza/expertiza#1079]
Exporting course participants and assignment participants do not share the same UI, may also not the same code. The exporting course participants UI should be the one we should use in both places. Plus, if we want to use the same code for both assignment participant and course participant models, we can put the code in participants.rb.

**Comment by nikolaygtitov** [comment]
Per latest test Exporting AssignmentParticipants and CourseParticipants share the same UI with two alternative options to export: 1) Export and 2) Export Details.
This issue can be closed, unless there are some additional problems reported/found.
