### ISSUE TITLE
Same review appears multiple times in the list of reviews

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1093]
This was posted last night (Nov. 10) by yzhan101:

![image](https://user-images.githubusercontent.com/127445/32690040-bd20a5dc-c6bd-11e7-8e8e-8a19c32449a2.png)

And this was reported 8 hours earlier by apatial:

"I by mistake requested for the same project for review for the second time.It was my 4th review selection. How do I undo this error as I'm not able to select any more reviews ?
Can that review selection be deleted ?"

They seem to be two occurrences of the same bug.  I think I've seen this bug before.

**Comment by efg** [comment]
This screenshot from cshao seems to suggest that the problem may be related to E1793:

"We can submit 4 reviews according to assignment policy. But the forth one of my reviews is not able to be edited or submitted. I even can not view it any more. I applied for a fifth review, and submitted it. But I don't know how to deal with the forth one. I'm not sure this problem will influence my points or others."

![image](https://user-images.githubusercontent.com/127445/32690101-8a0b0164-c6be-11e7-94a0-98fb6498ca6e.png)

**Comment by saratkavuru** [comment]
Looks like E1793 has 2 slots. So , is it possible that the reviews allocated refer to the same topic but different submissions?

**Comment by Winbobob** [comment]
Currently, the issue is fixed. But we need log visualization to find the root cause.

**Comment by efg** [comment]
Indeed, have just verified that this is fixed, for Final Project in Spring 2019.

But, it could still be intermittent.
