### ISSUE TITLE
View scores fails because rubric was changed?

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1096]
View scores for Rona Tyger's test assignment (https://expertiza.ncsu.edu/grades/view?id=875), created during the TLT Group demo on Oct. 28 & Nov. 16, 2017, doesn't work.  I suspect this is because I changed the review rubric to something more reasonable, not realizing that reviews had been done.

An instructor should be warned about changing the rubric if there are outstanding reviews.

(It would be pretty difficult to fix the system to allow rubrics to change, because then each review would have to remember which rubric it used.  Now it just knows what assignment it is associated with.)

**Comment by efg** [comment]
Maybe it would be better to ask the instructor whether to delete previous reviews, & if so, tell the students to redo those reviews because the rubric has changed.

**Comment by johnbumgardner** [comment]
E2110 resolves this.
