### ISSUE TITLE
Round 2 review can't be updated

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1097]
This situation occurred to user skumar24 in assignment 843 (Madeup problem).  

She submitted her review late (on Nov. 18, when the first review deadline was Nov. 17).  So she got the 2nd-round review rubric.  After this, the authors resubmitted their work.  But she was not able to Update her review, as she should have been.  She could not even Edit her review (and indeed, she should not have been able to, because it had been Submitted).  So she was unable to review the resubmission.

This was a staggered-deadline assignment, which may be part of the problem.  When an author resubmits, then reviewers should be able to Update (not Edit) their reviews, even if those reviews have already been submitted.

**Comment by efg** [comment]
Related to the "[Warn of deadlines and enforce them](https://docs.google.com/document/d/1hugCK-X2LB1um-xvHm8cdMwuEiayqQC8JY_BGY_bs7s/edit#)" project.

**Comment by Saurabh110** [comment]
It works correctly now.
