### ISSUE TITLE
Improvements to imports

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#110]
When a form is imported, if a column is missing, an error occurs.  Sometimes, depending on what is imported, this can be a Rails error.  This should be fixed.

Also, it would be more user-friendly if a user could just import a list of users, participants, topics, etc.; the system would then display what was imported, and let the user choose from a dropdown which field was which.  The default ordering would be the same as what is currently required by Expertiza.  I've seen this in a number of other educational apps.  Would be nice to have it in Expertiza.

Includes issues #13 and #52.

**Comment by yangsong8** [comment]
E1656 rejected.
