### ISSUE TITLE
The page "grades/view" is taking too long to load.

### ISSUE THREAD

**Issue by Kunalkul1** [expertiza/expertiza#1121]
The reason for the slow loading of the page is that the data for all the teams is loaded as soon as the page is loaded. Instead, what could be done is that the data for each team can be loaded when the expand button for that team is clicked. The existing code consists of a for loop in views/grades/_teams.html.erb, which renders the partial "views/grades/_tabbing.html.erb" which displays the data repeatedly. Instead, this partial could be rendered through AJAX or JQuery, whenever the expand button is clicked. This would save redundant loading of data and thus reduce the loading time of the page.

While implementing this fix, we first created a controller method, which would render the required partial "views/grades/_tabbing.html.erb" when called. We passed the required data through the Rails params hash. However, since one argument that needed to be passed (tscore) is a Hash, when it enters the params hash, it is getting converted to a String. We tried passing the hash as it is, but after doing this all the data in the hash is not retained, i.e. there is a loss of data. We also tried converting the String back into Hash by using the eval method, and to_unsafe_h method. However, these methods require the hash to be present in a normal form i.e. key value pairs. But our hash has values as Objects, thus these methods cannot be applied. Thus, we are unable to access the data in the String-hash. If this could be done, then our approach would result in successfully decreasing the loading time of the webpage.

**Comment by johnbumgardner** [comment]
this was sort of remedied with upgrading to rails 5.1, but not exactly a bug that we should be tracking.

expertiza running better is always a goal.
