### ISSUE TITLE
All javascript files in /assets/javascripts/ are loaded in every page.

### ISSUE THREAD

**Issue by ferryxo** [expertiza/expertiza#1139]
All javascript files in /assets/javascripts/ are loaded in every page, although not all of these scripts are needed in every page. This sometimes create some bugs because developers thought that they are not supposed to be loaded everywhere. We should clean this up, and create separate folders for page specific scripts and scripts that to be loaded in every page.

**Comment by efg** [comment]
This should be handled during front-end/back-end separation.
