### ISSUE TITLE
Due dates timeline for planning new releases by the developers 

### ISSUE THREAD

**Issue by ferryxo** [expertiza/expertiza#1140]
Until now, the developers can't plan when to release and deploy a new feature. sometimes new features get released when there is a course having a deadline. This is very risky. We could lose data that is being entered by the users. The new features are usually buggy. having a buggy system when students are having a deadline, really disturb them. 

The admin and developers need to have an overview of the due dates of all courses by day, week, and month so they can plan a better time to release new features. Even better, if these events can be visualized with Google calendar.

**Comment by efg** [comment]
I think the purpose may be subsumed by canary release.  Not sure this is a high priority, and it may be redundant.

**Comment by ZachariahMathews** [comment]
We do not want to support a developer feature in Expertiza.
