### ISSUE TITLE
Summative rubric is lost when rubric changed to not varying by round, and later changed back again

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1173]
If an assignment is rubric-varying-by-round and then mistakenly changed back to be not varying by round, and then corrected to be varying-by-round again, the formative rubric is applied to _all_ rounds.  Of course this is incorrect; they summative rubric should be re-enabled for the summative round.

The problem is that when you make an assignment rubric-varying-by-round, the Javascript just assumes that the summative review is the same as the formative review.

AJAX should be added to fetch the summative review ID from the db (it’s still there, because we assume the assignments_questionnaires table entry hasn’t been removed).

This needs to be fixed.

**Comment by efg** [comment]
No, now what happens is that when you change back to varying by round, the rubrics no longer appear in the dropdowns (you get just ----------), but you can go back and reselect the rubrics in the dropdowns and everything is cool.

So, there needs to be a fix so that the rubric names aren't removed when the # of rounds changes.

**Comment by Saurabh110** [comment]
Fixed in 43c98f4c4ca2ef463ed3be5cf93cad18913c5af3
