### ISSUE TITLE
Deleting an administrator does not work

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1187]
When deleting an administrator, e.g., ECE306_team26, a confirmation box comes up, and then when I click OK, it takes me back to the homepage.  But it does not delete the administrator.

**Comment by efg** [comment]
Deleting an instructor doesn't work either.

**Comment by ZachariahMathews** [comment]
Creating an administrator works now. 

Deleting administrator and instructor is not defined now. Is it similar to delete user? Or do we need to handle more stuff, like making blank the parent_id of users created by the instructor/admin?

**Comment by efg** [comment]
Deleting an administrator does work from the Manage Users screen.

It is not "List Administrators", but rather, Administration > Show > Administrators.

If you go to Administration > Show > Administrators, and click on one of the administrators, and then Delete that administrator, you will get a message that the admin was deleted, but alas, the admin that you thought you deleted will still be in the list of administrators.  (And it is still a real administrator, because you can delete it from the Manage > Users screen!)

**Comment by Saurabh110** [comment]
The method to remove an admin has been removed from the code in commit 1ef379047cc83580e3bb0718ed5ab4b24dc79f69
