### ISSUE TITLE
Self-introduction of new users

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1196]
There is a "Self Introduction" (without the hyphen) box on the page for creating a new user.  This doesn't make any sense unless someone is creating their own account, which of course, they would not be doing.  The purpose of this box is not clear ... who would see the introduction?

I think it should just be removed.

**Comment by ZachariahMathews** [comment]
Should we keep the self introduction text box while requesting for an account (instructor/TA) from the login screen?

**Comment by Winbobob** [comment]
This pull request was merged.
