### ISSUE TITLE
When a student clicks the check mark on a topic in the bidding interface, an error occurs

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1208]
When a student clicks the check mark on a topic in the bidding interface, an error occurs.  First, the student is taken to a screen that says, "Sign up user".  If the user enters his/her username in the box and clicks, "Submit", a Rails error occurs.

**Comment by TheAkbar** [comment]
This issue can be resolved by if this [line](https://github.com/expertiza/expertiza/blob/master/app/views/sign_up_sheet/_topic_names.html.erb#L10) is placed in a conditional that checks if this assignment enables bidding:
`
<% if not @assignment.is_intelligent or ['Instructor', 'Teaching Assistant', 'Administrator', 'Super-Administrator'].
  include? current_user_role?.name %>
  <%= link_to image_tag('signup.png', :border => 0, :title => 'Sign Up Student', :align => 'middle'), signup_as_instructor_sign_up_sheet_index_path( assignment_id: params[:id], topic_id: topic.id) %>
<% end %>
`

However, regardless of whether or not bidding is enabled, this check mark causes an error when clicked by a student. I'm not sure why this is available in the student view.

**Comment by efg** [comment]
This bug cannot be reproduced, and may have been fixed.  Sort of.  The issue now is that you can't switch your assigned topic to another topic that has slots available.  But that is another issue.
