### ISSUE TITLE
Review not possible during resubmission period, even when explicitly enabled

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1211]
Currently, Program 2 (assignment 931) is not available for review, despite the fact that due dates are as follows:
![image](https://user-images.githubusercontent.com/127445/46706925-39b70a80-cc05-11e8-9430-3dada9e11e39.png)

Since it is between October 5 and October 10, and Review Allowed is set to "Yes", it should be possible to review.  But impersonating a user shows that it is not:

![image](https://user-images.githubusercontent.com/127445/46706956-771b9800-cc05-11e8-8dcd-ca86123daf5f.png)

**Comment by efg** [comment]
The current code at line 17 of student_task_controller.rb is clearly wrong, because it is intended to preclude any reviewing during a submission period, whereas the ability to review during submission periods is supposed to depend upon assignment settings.  Varun's commit would fix this problem if it were merged, but it was not merged due to a failing test.

**Comment by efg** [comment]
This issue is noted as still extant, when I tried to allow review before the submission deadline in Program 2 (Assignment 991).

**Comment by Saurabh110** [comment]
Fixed by 7de23051e6bc8891c6f7b4c9ca680bd44501e1ae
