### ISSUE TITLE
A review deadline should be optional

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1218]
Since CATME is no longer free, I have begun using Expertiza for assignments that have teammate reviews, but not peer review of other teams' work.  In this situation, it is very confusing to have a review deadline.  Students try to review and are told that no work has been submitted for them to review.

If the review deadline were optional, it could simply be omitted when work was not to be peer-reviewed.

**Comment by akshayravichandran** [comment]
Fixed here https://github.com/expertiza/expertiza/pull/1419
