### ISSUE TITLE
Editing the title of a rubric gets saved with the "Update" button, not "Save review questionnaire" button

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1244]
This is very non-intuitive.  The "Save" button should save the new title, not just the changed questions!

**Comment by efg** [comment]
![screen shot 2018-10-24 at 5 28 15 pm](https://user-images.githubusercontent.com/127445/47462793-66952100-d7b2-11e8-93e1-8dc028774e39.png)

**Comment by akshayravichandran** [comment]
Fixed here https://github.com/expertiza/expertiza/pull/1417
