### ISSUE TITLE
Problem importing metareviewers from csv

### ISSUE THREAD

**Issue by nilbus** [expertiza/expertiza#13]
Xuezhou Ma xma2@ncsu.edu Re: Metareviews impossible too

Also, does assigning meta-review follows the EXACT same format as assigning regular review (shown in Chapter set 3.xls)? I worked out the meta-reviewer list, but it gave me some error when I tried to import the .csv file. I believe it is a format thing.

The excel generated csv (comma based): http://tinyurl.com/27c4a4u

The error shown is below:
Error!

The following errors were encountered during import.
Other records may have been added. A second submission will not duplicate these records.
Contributor, S30, was not found.
Contributor, S30, was not found.
Contributor, S30, was not found.
Contributor, 3a, was not found.
Contributor, 3a, was not found.
Contributor, 3a, was not found.
Contributor, 3b, was not found.
Contributor, 3b, was not found.
Contributor, 3c, was not found.
Contributor, 3d, was not found.
Contributor, 3d, was not found.
Contributor, 3d, was not found.
Contributor, 3e, was not found.
Contributor, 3e, was not found.
Contributor, 3f, was not found.
Contributor, 3f, was not found.
Contributor, 3f, was not found.
Contributor, 3g, was not found.
Contributor, 3g, was not found.
Contributor, 3h, was not found.
Contributor, 3h, was not found.
Contributor, 3h, was not found.
Contributor, 3i, was not found.
Contributor, 3i, was not found.
Contributor, 3i, was not found.
Contributor, 3j, was not found.
Contributor, 3j, was not found.
Contributor, 3j, was not found.
Contributor, , was not found.
Contributor, , was not found.
Contributor, , was not found.
Contributor, , was not found.
Contributor, , was not found.
Contributor, , was not found.
Contributor, , was not found.
Contributor, , was not found.
Contributor, , was not found.

**Comment by efg** [comment]
This was addressed by E1776, which was merged, but I see a cryptic message,
"Sequence of columns in file:
  1. Contributor
  2. Reviewer
  3. Metareviewers"

But the file contains only one column!

**Comment by efg** [comment]
Importing meta-reviewers **does** work now, but it gives this evidently spurious error message after the import:
"The following errors were encountered during import.
Other records may have been added. A second submission will not duplicate these records.
undefined method `id' for nil:NilClass"

**Comment by johnbumgardner** [comment]
This works now. Use the team name
