### ISSUE TITLE
Course student grade summary calls topics by primary key!

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1336]
The https://expertiza.ncsu.edu/assessment360/course_student_grade_summary from Project E1871 lists topic "numbers" and titles.  But for the number, instead of using the "Topic ID" (known as the "topic_identifier" field in the sign_up_topics table), it uses the "id" field of the sign_up_topics table, which is just the primary key of the record!

An easy fix, which should be made.

**Comment by Winbobob** [comment]
Fixed by pull request #1343.
