### ISSUE TITLE
In assignment creation, course dropdown is too narrow

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1340]
When a new assignment is created, there is a dropdown to select a course.  However, the field is too narrow, and the last character in the field is cut off.  This is really bad if, as usual, this character is the last character of the year that the course is offered.  You can't tell in which semester you are creating the assignment.

**Comment by nikolaygtitov** [comment]
Test server is used in the attempt to reproduce this issue. While creating new assignment and editing newly created (existing) assignment the course dropdown found to be at normal size (e.g. not too narrow):

![temp](https://user-images.githubusercontent.com/8548602/62801950-d6139d00-bab4-11e9-8d24-bfaa9fca9619.png)

As it can be observed from the above screenshot, in fact, course dropdown is the same size as other dropdown boxes.
Maybe this issue depends on the browser being used. I used for all the testing Chrome and Firefox. Neither browser shows any problems.
