### ISSUE TITLE
Assignments with "Use dropdown instead" cannot be saved

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1352]
When you try to use "Use dropdown instead" for author feedback and teammate reviews, when you save the assignment you get told that the assignment could not be saved.  And when you open it again, the "Use dropdown instead" checkboxes are not even checked.

**Comment by nikolaygtitov** [comment]
This issue still exists partially. When I clicked "Save" button with "Use dropdown instead" checkboxes checked, I did not see any problem (e.g. assignment could not be saved). Instead, I saw that assignment was successfully saved (e.g. green box). However, when I went back to "Rubrics" tab to see if checkboxes were still checked, they were NOT. Thus, this is still a bug and needs to be fixed.

**Comment by Saurabh110** [comment]
Fixed by E1970 (#1534)
