### ISSUE TITLE
Creating one assignment, I was dropped into another assignment!

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1354]
I was creating a new "OSS project and documentation" assignment, which, it turns out, is assignment 967.  I filled out the General tab and hit Save.  I was surprised to find that I landed on a page with all the rubrics already specified!  I had landed in the middle of assignment 908!

I was able to go back to the list of assignments and select the assignment I'd just created, which got me successfully back into assignment 967.  But someone who didn't realize that they were in a different assignment would be very worried ...

**Comment by efg** [comment]
See [Issue #1582](https://github.com/expertiza/expertiza/issues/1582), which is the same problem.

**Comment by SaNPai23** [comment]
Duplicate issue, fixed in commit # 9fb340c.
