### ISSUE TITLE
Meta-review limit keeps showing up, even when unchecked on the Review Strategy tab

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1355]
If the instructor is setting up an assignment and doesn't want the students to do meta-reviews, and unchecks the "Has Meta-review Limit?" checkbox on the Review Strategy tab, and then saves the assignment, when (s)he goes back to the Review Strategy tab, the "Has Meta-review Limit?" box will be checked again!  It's impossible to turn it off.

**Comment by johnbumgardner** [comment]
#1801 is a similar problem

**Comment by efg** [comment]
This is the same as #1801
