### ISSUE TITLE
Unable to add a team member to a team as an instructor

### ISSUE THREAD

**Issue by akanksha0625** [expertiza/expertiza#1360]
Facing an error when trying to add a team member to an existing team.

Steps to replicate:
1. Login as an instructor.
2. Go to Assignment tab under Manage.
3. Click any assignment for example : OSS project & documentation.
4. Select Create Teams.
5. Select Add Team Member option for any team.
6. Enter the user login information of the student to be added.

Getting the below error:
![error on adding team member](https://user-images.githubusercontent.com/43586277/53687525-88c02200-3d03-11e9-91fa-37742a281d83.JPG)

**Comment by efg** [comment]
Issue #91 is related: Adding a nonexistent user to a team causes traceback.

Adding a nonexistent user should generate a readable error message.
