### ISSUE TITLE
Instructor should be able to choose where to see assignment actions

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1384]
On an instructor's/admin's/TA's homepage, in the assignment list, there are three rows of icons for performing several operations on the assignment.   Ferry didn't like this, so he added a "Other stuff" (renamed to "Etc. ...") tab where all of these actions are available by clicking tiles.  The icons for the actions are in the tiles in rather ugly fashion, but that's another issue.

I think an instructor should be able to choose whether to see these actions on the homepage or on a tab associated with each assignment.  So there should be a setting in the Profile that controls this.

**Comment by Saurabh110** [comment]
Fixed in Pull Request #1796
