### ISSUE TITLE
How do we get to see a tone-analysis report?

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1392]
I've seen a grid rating the sentiment of review comments, but I can't find it now.  Is it still accessible from the UI?

**Comment by efg** [comment]
The call has been removed from the code, although the code for the report still exists in popup_controller.  It was in the system in May 2018.

See

- 83de1f4218ea6ae61d1bc4ab74efa9cf560f7810
- dc574043a903a54e337bdcd2306c2fae8007b2c6
- 87757aba339357364098c6c0113ffc78c96c2a4e

**Comment by johnbumgardner** [comment]
This is no longer needed. Not important.
