### ISSUE TITLE
TAs can't use anonymized view; why not?

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1404]
sseelam2 has a TA account, but her Manage menu does not have the "Anonymized view" option.  It seems like TAs should be able to use anonymized view.

**Comment by nikolaygtitov** [comment]
The test server is used to reproduce the issue. That specific user/TA does have "Anonymized view" option as displayed below:

![temp](https://user-images.githubusercontent.com/8548602/62798113-7d8bd200-baab-11e9-939c-0242104a177c.png)

In fact all the TAs that I impersonated have this option.
If problem exists it is hard to reproduce it. I think the issue can be closed.

**Comment by efg** [comment]
This has been fixed now.
