### ISSUE TITLE
Malformed topic does not get imported, even though confirmation page says it will be imported

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1408]
My topics.csv file had this line:

E1925,"Refactor E1858,"Github metrics integration",1

You can see that it has an extra quote mark in it.  The confirmation page said it would be imported, and that the topic number would be "E1925,"Refactor E1858".  But it did not get imported at all.

If it's on the confirmation page, it should be imported.

**Comment by Saurabh110** [comment]
You don't need quotes since it is a csv file.
The importing functionality seems to work properly now.
