### ISSUE TITLE
There needs to be a way to remove a lot of topics quickly

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1409]
I often copy assignments from one semester to the next.  When I copy an assignment with topics, the topics get copied too.  But this is usually wrong ... topics typically change from one semester to the next.  So,

- one should be able to copy an assignment without copying the topics, and
- there should be a way of deleting all the topics of an assignment with a single UI action, so you don't have to delete them one by one and wait for the refresh, then switch tabs for each topic.

**Comment by Saurabh110** [comment]
Fixed by pull request #1524
