### ISSUE TITLE
Import assignment participants does not work!

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1411]
I have tried to import assignment participants.  I can get to the confirmation screen that shows me which users are going to be imported.  But when I click on "Import Participants" at the bottom, the participants list refreshes, but the new users have not been imported.

This must be a recently introduced bug.

**Comment by nikolaygtitov** [comment]
I have tried to import assignment participants using .csv file with two following entries:
aliceanga | Alice Anga | aaa@ncsu.edu | aaaaa
bobboster | Bob Bobster | bbbbb@ncsu.edu | bbbbb

Where '|' is the tab character in the .csv file. In the "Import AssignmentParticipant List" page, choose Tab as delimiter.
After confirming the import, I observed that only second record was imported (bobboster). No track of the first entry was found. There is definitely something is wrong with importing. Needs to be checked and tested with single and many entries.

**Comment by efg** [comment]
Ed was able to import participants successfully, so this bug is apparently intermittent, or affects some users and not others.  Both of us were using Chrome on Windows 10.

**Comment by efg** [comment]
Another confirmation that the bug is intermittent: Nikolay is able to import tonight, was not able to do so yesterday.

**Comment by efg** [comment]
I just tried to import participants to CSC/ECE 517 Program 2, and was not able to.  Same situation as on March 27.

**Comment by efg** [comment]
Same problem in adding participants for the final project.

**Comment by Saurabh110** [comment]
Could you please provide the csv files, so I can see what went wrong.

**Comment by Saurabh110** [comment]
Try to add an automated test.

**Comment by johnbumgardner** [comment]
It works now! Both on beta and master
