### ISSUE TITLE
Bugs with assignment teams

### ISSUE THREAD

**Issue by akshayravichandran** [expertiza/expertiza#1420]
The following bugs were noticed in the CSC/ECE 517 Spring 2019 Final project (and design doc):
1. 2 teams had 5 members, including one member who was present twice.
2. An “Expertiza Internationalization” team was on a waitlist in 2 places (for the same topic), and yet, it was not found in the list of teams!
3. sbhadau was a member (actually, the sole member) of 4 teams.

**Comment by Saurabh110** [comment]
The issue (primarily caused because of multiple clicks) has been resolved in commit #7994677
