### ISSUE TITLE
Review refuses to load after user swipes across touchpad

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1425]
With Firefox Quantum 65.0.1 on MacOS 10.14.1, when the user swipes across the screen in order to use the touchpad to switch windows, a message "Loading" appears, and the browser seems to hang.  It is not possible to get control back to edit or save the review; however, the review is still auto-saved.

**Comment by Saurabh110** [comment]
Same as #1356

**Comment by Saurabh110** [comment]
Fixed in 6ca144b17376897999ddb0db1feaa0832647a812
