### ISSUE TITLE
User on two teams at one time

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1426]
For the Final Project assignment, Bill Mwaniki was on two teams.  Here is the screenshot showing him being on his solo team
![image](https://user-images.githubusercontent.com/127445/55654349-2a350a80-57bf-11e9-9216-c7af1128089f.png)

And after he left that team, the "Your team" page showed him on his real team:

![image](https://user-images.githubusercontent.com/127445/55654373-3ae58080-57bf-11e9-93f5-7a3503cfbf91.png)

How could he be on two teams?  You are supposed to have to drop off one to join another.

**Comment by Saurabh110** [comment]
The issue (primarily caused because of multiple clicks) has been resolved in commit 7994677
