### ISSUE TITLE
Same submission assigned to the same reviewer twice

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1431]
Four times this semester, we have encountered situations where students have the same team listed twice in their list of reviews to be done.

Here is one student (ssiddha)'s impression of how that happened:

I requested normally from the list and I was presented with duplicate reviews. I tried to see what was happening from the "Network Tab". Here are my observations:
It looks like sending multiple requests with the same data parameter adds the reviews to user's account
In my case, I guess submit button was pressed twice (in turn 2 requests were sent) and the back end did not check whether this project is already assigned or not.
I initially thought that this could be concurrency issue, but doesn't look like one. Based on my observation from the code base, there is no check once the request is sent from the user.
To replicate the issue:
Use any standard Proxy (Ex: Burp, OWASP ZAP)
Intercept the request and send this request to repeater
Use the repeater to resend the request as many times as required
You can also reproduce from using API development environment like Postman (In this case, we may have to add all the parameters and send the request as needed)
Please let me know if my explanations are not sufficient

**Comment by Saurabh110** [comment]
Currently fixed in commit 7994677
