### ISSUE TITLE
Error when creating a new policy

### ISSUE THREAD

**Issue by aaltaf3** [expertiza/expertiza#1435]
When editing an assignment, I clicked on the "New late policy" link in the "Due dates" tab. On the "New late policy" page, I entered the following information:  
Late policy name: Policy 1
Penalty points per unit: 10
Penalty unit: Day
Maximum penalty: 50
The following error message is displayed on the top of the page and the policy is not added to the list of policies: “The following error occurred while saving the penalty policy:”

**Comment by SaNPai23** [comment]
Error was caused due to invalid action, was just not being displayed.
Added the error message which was being raised.
