### ISSUE TITLE
The "+" and "-" buttons for Show/Hide Date Updater do not work

### ISSUE THREAD

**Issue by aaltaf3** [expertiza/expertiza#1437]
In the "Due dates" tab when editing an assignment, I clicked on "Show/Hide Date Updater" which displayed an input box with a "Days" label and "+" and "-" buttons around the input box. The "+" and "-" buttons are not functional.

**Comment by aaltaf3** [comment]
In the "Due dates" tab when editing an assignment, I clicked on "Show/Hide Date Updater" which displayed an input box with a "Days" label and "+" and "-" buttons around the input box. The "+" and "-" buttons are not functional.

**Comment by Saurabh110** [comment]
This feature does work. One has to check boxes in front of the dates for which this feature is desired to be used.

Project Link - https://expertiza.csc.ncsu.edu/index.php/CSC/ECE_517_Fall_2016/E1654._Improve_date-picker_and_deadlines
