### ISSUE TITLE
Add participant fails after adding a participant to course with no assignments

### ISSUE THREAD

**Issue by Mandhani** [expertiza/expertiza#1466]
Getting a NoMethodError when doing this:
1. Add a course, Do not add an assignment to this course.
2. Add a participant to this course. On clicking add, this does not give any result/feedback. On clicking add again, it gives an error "The user ksm3 does not exist or has already been added." The user seems to be added. But does not show up on the list.
3. Going back to course list page and trying to add another participant to this course, gives a NoMethodError in Participants#list. The exact error is: undefined method `has_badge?' for nil:NilClass.
The issue seems to in /home/expertiza_developer/expertiza/app/views/participants/_participant.html.erb at line #8:
<% if participant.assignment.has_badge? %>

The following fix seems to fix the issue but needs testing: 
Replace line 8 in the above mentioned view file with this line: <% if !participant.assignment.nil? && participant.assignment.has_badge? %>
We just added a check to see if assignment is null, which it is in our mentioned scenario.
Screenshot of error:
![image](https://user-images.githubusercontent.com/47258154/56994503-4a14df80-6b6d-11e9-8255-5c8d48298708.png)

Contact issue reporter at: mkushal@ncsu.edu

**Comment by efg** [comment]
This bug has apparently been fixed.  Participants can now  be added to courses with no assignments.
