### ISSUE TITLE
Weird column spacing 

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1472]
The View Scores report for Madeup Problem (assgt. 953) has columns too narrow to view even one character of text!

**Comment by nikolaygtitov** [comment]
The test server was used in the attempt to reproduce the problem:
http://152.7.99.47:3000/grades/view?id=953
No problems were observed viewing grades report for the assignment 953. Moreover, no problems were observed viewing grades report for any other assignment.

**Comment by efg** [comment]
Indeed, I have not seen this problem recently.  Let's assume it's fixed.
