### ISSUE TITLE
There is no way to save changes in user permissions

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1474]
If I import participants, they will be granted all permissions (submit, review, read) for an assignment.  I can change this from the participants screen (.e.g., https://expertiza.ncsu.edu/participants/list?id=982&model=Assignment) by using the dropdowns to the right of each user name.  _But there is no way to save these choices._  When I navigate away from the page and back to it again, all of the participants will be plain "participants" again (not, e.g., "submitters").

There needs to be a way to save these changes!

**Comment by efg** [comment]
That is, there is no way to save changes in the user's profile.

**Comment by Saurabh110** [comment]
_participant_html.erb.
There is a submit button corresponding to each participant, which records your response from the dropdown parameters (which changes the user permissions). Changed the opacity of this submit button to 1 (Which for some reason was set to 0 ).
