### ISSUE TITLE
Problems adding members to teams

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1476]
I just added the authors to the WCAE 2019 teams  The following problems were noted.
* Adding a member from the UI (typing the ID into the textbox) raises an error, as it has for a few years.
* I was unable to impersonate the placeholder users (p1, p2, p3, ..., p9).  Trying this from either my account or the admin account caused an error.
* I was able to import the users, but there were glitches even here.  If I did not include a comma at the end of the line, Expertiza reported that there were not enough fields.  If I did include a comma, Expertiza told me that the user "" did not exist, and asked me if I wanted to create this user.  This prevented me from importing more than one team at a time (each team needed to be written to a separate file).

**Comment by Saurabh110** [comment]
Could not reproduce.
None of the above steps got erorred.
