### ISSUE TITLE
Review report should link to the usual view for reviews

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1478]
Stacie Ringleb writes,

> We’re looking at the peer reviews my students conducted on an assignment.  If I impersonate a user, I can see what they wrote in their report evaluations.  However, if we are in the assignment and select review report, the reviews show up in html (or something that looks like that).  Should we be picking a different option to view the peer reviews.  This assignment is MAE_434W_SU19_intro.

It turns out that the review report uses its own code to display reviews, and not only it it a pretty basic view, it doesn't even interpret HTML codes!  It should be changed so that it calls the usual code that is used for displaying reviews, that gives the circle with the score inside, etc.

**Comment by Saurabh110** [comment]
Fixed in #1805
