### ISSUE TITLE
Varun's analysis of outstanding issues

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1479]
This was in email from May 8:

When # of review rounds is reduced, student can no longer view scores	#1331 opened on Dec 11, 2018 by efg
Assignment is not reviewable even though it is during the review period ...	#1321 opened on Dec 7, 2018 by efg
Self-review is doable even after being submitted	#1221 opened on Oct 15, 2018 by efg
Review not possible during resubmission period, even when explicitly enabled	#1211 opened on Oct 9, 2018 by efg
Review that was not done is given a score of 50%!	#1145 opened on Mar 9, 2018 by efg Priority 3
Verify score view is not being used anywhere in the system and delete it. 

Only some of the issues were reproducible. I have issued the following pull requests which fix the reproducible issues:
Delete score views: 1439
Close #1439 - Cannot give author feedback or teammate reviews 1432
Close #1211 - Review not possible during resubmission period, even when explicitly enabled: #1373

**Comment by Saurabh110** [comment]
Resolved all the mentioned issues and PRs
