### ISSUE TITLE
Dropdown seems to be the default for bookmark rating, but not for any other kind of rubric

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1484]
It seems that when bookmarks are enabled, the default way to evaluate them is through a dropdown, not a rubric.  It's not clear whether assigning a bookmark-rating rubric would even work.

Should the default for bookmark ratings be a rubric, just like the default for everything else that needs to be evaluated?  (work, reviews, team-member contributions)

**Comment by johnbumgardner** [comment]
This seems to have been resolved
