### ISSUE TITLE
Cannot create an assignment that is not in a course

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1487]
Currently, if I create an assignment, it comes up saying it is assigned to some course.  I can scroll the dropdown and select that it is not assigned to any course "-----------".  But when I reload the assignment, it still says it's assigned to that course!

**Comment by Saurabh110** [comment]
Every assignment is supposed to be associated with a course, is this correct? or am I missing something?

**Comment by efg** [comment]
No, you can create free-standing assignments.  However, it seems that if you are admin, it automatically picks a course for them!   It doesn't do that if you're an instructor, but then it may tell you that the assignment couldn't be saved (and save it nonetheless).

**Comment by Saurabh110** [comment]
Free-standing assignment creation is working.
