### ISSUE TITLE
"Additional comment" does not show up in heatgrid

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1488]
The "additional comment" in a review can be seen only by expanding the whole review (e.g., if the instructor clicks on the reviewer's name, or if the student clicks on the reviewer's number).  This is so well hidden that many authors undoubtedly miss it completely.

There should be an extra link in the bottom row of the heatgrid that brings up the comment.

**Comment by Saurabh110** [comment]
![image](https://user-images.githubusercontent.com/54721827/88715702-f08ebe00-d0eb-11ea-94b6-25a18c5cd53d.png)

Additional comment for every review is clearly visible as seen in above image.
