### ISSUE TITLE
In heatgrids for many assignments, the round # does not appear

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1489]
Here is an example from Assignment 897:

![image](https://user-images.githubusercontent.com/127445/62504919-8be69f00-b7c8-11e9-932d-a8e6818e9642.png)

**Comment by Saurabh110** [comment]
This is working fine for new assignments. Probably some bug caused older entries in 'used_in_round' column of Assignment_Questionnaire table to be 'null'.
