### ISSUE TITLE
It should not be possible to assign a reviewer who is not already a participant in the assignment

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1491]
... but currently, it is!

Also, the person added as a reviewer (on the Assign Reviewers screen) should have the right to perform reviews (i.e., not be just a submitter or a reader).

**Comment by Saurabh110** [comment]
Added a condition to check if the user is authorized or not (Has reviewing rights or is participant in the assignment.
Also added a check to handle condition when user enters empty string

**Comment by efg** [comment]
Is there a way to generalize this check?  Are there other places where a
user-ID is entered, and it must not be null?  Better to centralize that
check in a method of, say, user, rather than to require the extra check to
be inserted at several places in the code.
