### ISSUE TITLE
For admin, when creating an assignment, the default course is BIT 115 2011 Spring

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1492]
When an ordinary instructor creates an assignment, the Course dropdown comes up showing "--------------".  But when an instructor creates an assignment, the Course dropdown comes up showing "BIT 115 2011 Spring".  Weird.

**Comment by efg** [comment]
That is true from my home computer, but not from my office computer!  Even with the exact same Expertiza deployment!  Go figure!

**Comment by Saurabh110** [comment]
Similar to #1487

**Comment by Saurabh110** [comment]
This caused because of the course 'BIT 115 2011 Spring' had a leading whitespace which caused it to appear above default '---------' course.
Applied validation for no whitespaces (leading and trailing) while course creation and removed them for the courses already in the database.
