### ISSUE TITLE
TAs don't see a list of courses they are TAing

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1496]
Issue #998 said that TAs were able to see courses that they were not TAing.  Well, that bug has been fixed, and then some.  Because now, evidently no TA, upon logging in, can see any courses.  They can only see the Assignments for the course(s) they are TAing.

For the sake of consistency, TAs should be able to see a course list just like instructors and admins can.

**Comment by Saurabh110** [comment]
TAs were unable to view private courses.
Changed some conditions in course_node.rb, so now TAs can view all courses including private ones which they are TAing.

**Comment by efg** [comment]
Thanks.  May be necessary to revisit that after the authorization utilities
project is merged.
