### ISSUE TITLE
Can't import new users as CourseParticipants

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1497]
Two instructors including me have been bitten by this bug:  When you try to import new users (without pre-existing user accounts) from a CSV file, Expertiza starts to import the list and then reports some error.  It seems that you can create the user accounts first by importing the file, and then go and import the participants.  But you should be able to create the user accounts by importing participants.  That does not seem to work.

**Comment by Saurabh110** [comment]
This issue is fixed by commit 20edb13974f4fb0744d487d04eae396693cc8ba0
