### ISSUE TITLE
Multiple teammates should be able to give separate feedback to reviewers

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#150]
Currently, author feedback is given by a _team_ to reviewers who have reviewed their work.  Jennifer Kidd, and perhaps other instructors, would like for _individuals_ to be able to give feedback to each of their reviewers.

From Jennifer Kidd: Individual students cannot respond to reviews given to teams. For example: Team A gets a review. All members of Team A should be able to respond to the review individually. This does not seem possible in Expertiza best we can tell, or, at least, many students have reported being unable to post a response to a review if their partner already did. This creates a problem for us because students are required to submit individual feedback to their reviewers

**Comment by yangsong8** [comment]
Also see #622

**Comment by efg** [comment]
Closed for now; access this via issue #622
