### ISSUE TITLE
Difficulty creating an assignment with topics

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1501]
Today, I tried to create an assignment with topics, and failed because I did not remember that the "Has topics" box does not appear until _after_ the assignment has been created (see Issue #1206).  

So then I copied an existing assignment with topics and tried to delete the topics, but I could not, because there were no action buttons.  (This may have been because the deadline for the assignment had passed ... not sure if I changed the deadlines before attempting this.)  So I deleted the topics with a db command, and then imported the new topics.

This probably isn't a bug at all, but it definitely indicates some usability issues!

**Comment by Saurabh110** [comment]
This is the expected behavior, mentioned in #1454.
