### ISSUE TITLE
Four reviews outstanding, when only two are allowed

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1503]
For Program 2 (assgt. 991), Omkar Kashid was able to have four reviews outstanding at the same time:

![image](https://user-images.githubusercontent.com/127445/66249416-197b3800-e701-11e9-8973-6415e084d189.png)

Yet, the assignment settings permit only 4 reviews max.

![image](https://user-images.githubusercontent.com/127445/66249421-3283e900-e701-11e9-982e-d161f52aa612.png)

**Comment by Saurabh110** [comment]
Probably caused because of the concurrency issue. Which is fixed in commit 79946775d9c35e4f381ed097a64b1603f414a4dd
