### ISSUE TITLE
Participants on multiple teams at the same time

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1509]
For Assignment 992, OSS project & documentation (Fall 2019), several users are on two teams right now:

drmakam -- on 3 teams
nnegi2 -- on 2 teams
rbharam -- on 2 teams
rdua2 -- on 2 teams
rnarasi2 -- on 2 teams
sadhika2 -- on 2 teams
schawan -- on 2 teams
skmatta -- on 2 teams
zding8 --  on 6 teams

The following are not only on more than one team; they are registered for more than one project!

rbharam  --  E1943 & E1955
schawan  --  E1943 & E1955
skmatta  --  E1943 & E1955
zding8 --  E1942 & M1951

**Comment by efg** [comment]
Now, there are two teams that have all three of you on them.  Each team is signed up for a different topic.  What happened that caused you to join two teams with the same members?  Knowing that will help us debug.
---
Comment from schawan:

Hello,
Nothing happened that we were able to notice. Everything went smoothly. The portal only showed us the topic "Refactor signup_sheet_controller", if anything would've happened that we would have noticed then we would have definitely let you know.
One reason I think is that during selection of the topic after the biding round I checked multiple topics, maybe that is the reason our team name ended up with multiple topics.

Thanks and Regards,
Saahil Chawande

**Comment by efg** [comment]
Comment from Benjamin Ding (zding8):

es professor, I do think it is a bug. Yesterday, when I tried to signup a for an assignment anyway, I found that E1952 had available slots, so I clicked on the Actions button, but nothing happened. Since it was so weird, I clicked the button for four times, only to find that the waitlist number increased to 4. At that time, I thought this was due to some algorithms not familiar to me. But now I believe it is a bug, maybe due to the specific button of E1952, because later I tried M1951 and successfully signed up.
Or possibly some crash or other things happened on the server at that specific time intant. Hope I can help you fix the bug!I would like to provide any further information you need.

**Comment by efg** [comment]
Just tested this.

If a user, without a team, clicks repeatedly on a signup sheet before the first response is received, then multiple teams are created for that user.

This is evidently because signing up for a topic triggers the creation of a team if the user who signs up is not on a team.

If a team signs up for a topic multiple times, the system behaves correctly, and signs the team up.  This is evidently because no team needs to be created, since the team already exists.

This explains how zding got on 6 teams, but it does not explain how rbharam, shawan, and skmatta wound up on the same two teams.

**Comment by Saurabh110** [comment]
Fixed the issue (primarily caused because of multiple clicks) has been resolved in commit 79946775d9c35e4f381ed097a64b1603f414a4dd
