### ISSUE TITLE
Instructor dropping teams from topics does not work

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1511]
The instructor is supposed to be able to drop a team from a topic by clicking the "x" next to the team name.

When I try this, I am flashed the message,

> You have successfully dropped the student from the topic!

But the team is still registered for the topic.

This was true for Assignment 922.

**Comment by Saurabh110** [comment]
![1](https://user-images.githubusercontent.com/54721827/83053339-948db780-a01e-11ea-976a-38d13101ab79.png)
![2](https://user-images.githubusercontent.com/54721827/83053358-99526b80-a01e-11ea-8a5e-480d250916d5.png)

It seems to be working. Please reopen the issue with a detailed explanation if this occurs again.
(PS - Could not find Assignment 922)
