### ISSUE TITLE
"Number of reviews left" message is misleading

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1516]
Look at swen4 on Program 2 assignment for CSC 517, Fall 2019.  It shows,

"Number of reviews left: 4"

whereas he has done all of his reviews.  This message is misleading!

**Comment by efg** [comment]
Ditto for this situation, where someone has done 4 reviews, only 4 are allowed, and it still says he has 1 left: https://piazza.com/class/jzhmtov8f26tp?cid=409

**Comment by Saurabh110** [comment]
This is caused when browsers back button is used to navigate on the review list and review edit page. It should display the correct value on refreshing the page. Couldn't reproduce the issue. Please reopen the issue if such a thing happens again.
