### ISSUE TITLE
There should be a way to import a list of who has signed up for which topic

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#153]
When a signup sheet is used in Expertiza, users are expected to sign up for topics.  But, the instructor might've taken signups offline, e.g., by passing around a signup sheet in class.  There should be a way to import this list to Expertiza, rather than impersonate all the students one by one and sign them up for a topic.

**Comment by yangsong8** [comment]
So, the import file type should be:
Team Name (optional), topic identifier (optional),Team Member1, Team Member2, ... , Team Member3

**Comment by yangsong8** [comment]
On revisiting this issue, sir, I think it would be better to import who should have a topic when an instructor creates topics by importing a file. What do you think?

**Comment by efg** [comment]
I don't see the difference.  Can you explain further?

**Comment by yangsong8** [comment]
So my question is, shall we import who is assigned to which topic when instructors import teams, or when instructor import topics? I feel the second might be better.

**Comment by efg** [comment]
I think it would be best to allow both.  Then we need to have some
real-time error checking for when a team is imported to a topic that is
already full.

**Comment by yangsong8** [comment]
I feel that assign topics while importing them might be a better idea. There are already several rough edges in importing teams functionality. So for E1717, I suggest we only ask this team do implement this feature in topic importing, is this okay?

**Comment by efg** [comment]
Allowing teams to be imported specifying a topic, and allowing topics to be
imported specifying  team … wouldn't cause any trouble.  We already allow
something similar, importing participants even if they don't have accounts,
providing that their e-mail address is specified so we can create accounts
for them.

I think a flexible import implementation will be best.

**Comment by yangsong8** [comment]
E1656 rejected.

**Comment by arjunssharma** [comment]
If TA is trying to import a file specifying the signed_up topic and the names of student, and the signed_up topic is not created so far, then do you want it to be created automatically and assign those students this topic or should it prompt an error saying that the topic doesn't exist?

**Comment by efg** [comment]
E1776 was merged, but it does not include this feature, even though the feature was in the specs for the project.

**Comment by efg** [comment]
It appears now that one can try to import a signup sheet (note: not "sign up sheet"), but when you try to import it, you get the message "There was a problem with the @model in app/views/import_file/show.html.erb".

**Comment by efg** [comment]
Sorry, this is not about importing topics; this is about importing people/teams signed up for topics.

**Comment by johnbumgardner** [comment]
![image](https://user-images.githubusercontent.com/38589044/124820293-46dec080-df3b-11eb-8614-45087a08f5dd.png)
Problem with importing signup

**Comment by johnbumgardner** [comment]
![image](https://user-images.githubusercontent.com/38589044/124820341-5f4edb00-df3b-11eb-91d1-20395b50b404.png)
from terminal

**Comment by johnbumgardner** [comment]
yeah this button functionality is not in expertiza, but there is a button for it. going to make the button invisible for the time being
