### ISSUE TITLE
Better help needed on format of file containing users to be imported

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#155]
Date: Wed, 7 Sep 2011 21:42:35 -0400

Subject: Re: Expertiza
From: efg@ncsu.edu
To: jessica_andrews@knights.ucf.edu

Hi Jessica,

I just imported the users for you.  Everything looks fine.  The only problem was the initial line

"  username, full name (first[ middle] last), e-mail address, password "

That was just a model line for you to use in creating the file.  It wasn't actually supposed to appear in the file.

**Comment by yangsong8** [comment]
E1656 rejected.

**Comment by yangsong8** [comment]
![image](https://user-images.githubusercontent.com/4420550/27234060-b208a1fc-5289-11e7-81a7-1c30b717cde0.png)

**Comment by efg** [comment]
But the message is clearer now (see above), and no one has had trouble in the last several years.
