### ISSUE TITLE
Course switched while assignment is being created

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1566]
Jennifer Kidd writes:

I am creating the final assignment for this fall. When I started to create it, I went into my Fall 2019 course, clicked +Assignment (selected Fall 2019) and added the title (final Wikibook Lesson), checked Available to students, and then clicked save.

This is what happened when I clicked Save. As you can see, the course switched to Spring 2018. So, I think you are right, there is something amiss with the create assignment script/process.

![image](https://user-images.githubusercontent.com/127445/67697562-221d0200-f97f-11e9-86a6-18cb3811db31.png)

**Comment by SaNPai23** [comment]
Fixing issue #1582  also solves this issue.
Refer commit# 9fb340c476820b1562f73c36ebbef2b130e47972
