### ISSUE TITLE
When students view reviewing grades, they are told their grade is "/100"

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1581]
When a student hovers over the info button in the reviewing column on the student homepage, it says that the review grade is out of 100.  This is wrong, grossly misleading, and a serious coding error.  In CSC/ECE 517, review scores are given in points.  10 points is the maximum that a reviewer can get for an individual review.  No one is allowed to do more than 4 reviews.  So the highest grade anyone can possibly get is "40/100"!

The "/100" needs to be removed!  I thought this had already been done.

**Comment by Saurabh110** [comment]
Minor change in student_task_helper.rb
