### ISSUE TITLE
In creating an assignment, you end up editing an old assignment of the same name!

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1582]
This happened to Jen in creating her second assignment this semester, and it just happened to me.  I was creating "Final project (and design doc)", assignment 1000.  But, up clicking "Create" (I wanted to save it so I would have the Topics tab), I got dumped into assignment 834, the assignment of the same name from Spring 2017!  Some things about it did not seem right, so I noticed right away.  But another instructor would not, and would end up (as Jen did) adding new students to an old assignment.

**Comment by SaNPai23** [comment]
Fixed in commit # 9fb340c476820b1562f73c36ebbef2b130e47972.
Changed assignments_controller.rb to ensure data for assignments is fetched by their id instead of their name(which caused the error).
Made appropriate changes in for spec files as well.

**Comment by efg** [comment]
Glad this is fixed!  Caused a lot of trouble last semester.
