### ISSUE TITLE
Error occurs when going to "Others' work"

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1605]
This problem occurs for user JWOOD051 (user 8275) in assignment 998: Clicking on "Others' work" gives an error page ("We're sorry ...").  Here are the relevant records in the db (text of comments has been elided for the sake of compactness:

`JWOOD051
User 8725
Participant 42998

response_maps
+--------+--------------------+-------------+-------------+-------------------+---------------------+---------------------+
| id     | reviewed_object_id | reviewer_id | reviewee_id | type              | created_at          | updated_at          |
+--------+--------------------+-------------+-------------+-------------------+---------------------+---------------------+
| 152442 |                998 |       42998 |       32249 | ReviewResponseMap | 2019-11-06 23:13:12 | 2019-11-06 23:13:12 |
| 152443 |                998 |       42998 |       32215 | ReviewResponseMap | 2019-11-06 23:22:15 | 2019-11-06 23:22:15 |
| 152444 |                998 |       42998 |       32135 | ReviewResponseMap | 2019-11-06 23:37:41 | 2019-11-06 23:37:41 |
| 152447 |                998 |       42998 |       32180 | ReviewResponseMap | 2019-11-07 00:02:01 | 2019-11-07 00:02:01 |
+--------+--------------------+-------------+-------------+-------------------+---------------------+---------------------+

mysql> select * from responses where map_id in (152442, 152443, 152444, 152447);
+--------+--------++---------------------+---------------------+-------------+-------+--------------+
| id     | map_id || created_at          | updated_at          | version_num | round | is_submitted |
+--------+--------++---------------------+---------------------+-------------+-------+--------------+
| 122551 | 152442 || 2019-11-06 23:13:26 | 2019-11-06 23:21:56 |        NULL |     1 |            1 |
| 122552 | 152443 || 2019-11-06 23:22:35 | 2019-11-06 23:37:22 |        NULL |     1 |            1 |
| 122553 | 152444 || 2019-11-06 23:37:45 | 2019-11-07 00:01:41 |        NULL |     1 |            1 |
| 122556 | 152447 || 2019-11-07 00:02:04 | 2019-11-07 00:18:05 |        NULL |     1 |            1 |
+--------+--------++---------------------+---------------------+-------------+-------+--------------+

mysql> select * from answers where response_id = 122551;
+---------+-------------+--------+-----------------------------------------------------------------+-------------+
| id      | question_id | answer | comments                                                        | response_id |
+---------+-------------+--------+-----------------------------------------------------------------+-------------+
| 1342175 |        6148 |      5 |                                                                 |      122551 |
| 1342176 |        6149 |      4 |                                                                 |      122551 |
| 1342177 |        6150 |      5 |                                                                 |      122551 |
| 1342178 |        6151 |      4 |                                                                 |      122551 |
| 1342179 |        6152 |      4 |                                                                 |      122551 |
| 1342180 |        6153 |   NULL | <p>The author's work is relevt permission to view it.&nbsp;</p> |      122551 |
| 1342181 |        6157 |   NULL |                                                                 |      122551 |
| 1342182 |        6155 |   NULL | NULL                                                            |      122551 |
+---------+-------------+--------+-----------------------------------------------------------------+-------------+

mysql> select * from answers where response_id = 122552;
+---------+-------------+--------+----------------------------------------------------+-------------+
| id      | question_id | answer | comments                                           | response_id |
+---------+-------------+--------+----------------------------------------------------+-------------+
| 1342183 |        6148 |      5 |                                                    |      122552 |
| 1342184 |        6149 |      5 |                                                    |      122552 |
| 1342185 |        6150 |      5 |                                                    |      122552 |
| 1342186 |        6151 |      5 |                                                    |      122552 |
| 1342187 |        6152 |      5 |                                                    |      122552 |
| 1342188 |        6153 |   NULL | <p>The graphics and layout hehis lesson.&nbsp;</p> |      122552 |
| 1342189 |        6157 |   NULL |                                                    |      122552 |
| 1342190 |        6155 |   NULL | NULL                                               |      122552 |
+---------+-------------+--------+----------------------------------------------------+-------------+

mysql> select * from answers where response_id = 122553;
+---------+-------------+--------+------------------------------------------------------------+-------------+
| id      | question_id | answer | comments                                                   | response_id |
+---------+-------------+--------+------------------------------------------------------------+-------------+
| 1342191 |        6148 |      5 |                                                            |      122553 |
| 1342192 |        6149 |      5 |                                                            |      122553 |
| 1342193 |        6150 |      5 |                                                            |      122553 |
| 1342194 |        6151 |      5 |                                                            |      122553 |
| 1342195 |        6152 |      4 |                                                            |      122553 |
| 1342196 |        6153 |   NULL | <p>The lesson was insightful and tture teachers.&nbsp;</p> |      122553 |
| 1342197 |        6157 |   NULL |                                                            |      122553 |
| 1342198 |        6155 |   NULL | NULL                                                       |      122553 |
+---------+-------------+--------+------------------------------------------------------------+-------------+

mysql> select * from answers where response_id = 122556;
+---------+-------------+--------+-----------------------------------------------------------------------------------+-------------+
| id      | question_id | answer | comments                                                                          | response_id |
+---------+-------------+--------+-----------------------------------------------------------------------------------+-------------+
| 1342215 |        6148 |      5 |                                                                                   |      122556 |
| 1342216 |        6149 |      4 |                                                                                   |      122556 |
| 1342217 |        6150 |      5 |                                                                                   |      122556 |
| 1342218 |        6151 |      4 |                                                                                   |      122556 |
| 1342219 |        6152 |      4 |                                                                                   |      122556 |
| 1342220 |        6153 |   NULL | <p>This work is relevant because uld be equipped with that information.&nbsp;</p> |      122556 |
| 1342221 |        6157 |   NULL |                                                                                   |      122556 |
| 1342222 |        6155 |   NULL | NULL                                                                              |      122556 |
+---------+-------------+--------+-----------------------------------------------------------------------------------+-------------+
`

**Comment by efg** [comment]
Let's try that again, without the paragraph tags.

`JWOOD051
User 8725
Participant 42998

response_maps
+--------+--------------------+-------------+-------------+-------------------+---------------------+---------------------+
| id     | reviewed_object_id | reviewer_id | reviewee_id | type              | created_at          | updated_at          |
+--------+--------------------+-------------+-------------+-------------------+---------------------+---------------------+
| 152442 |                998 |       42998 |       32249 | ReviewResponseMap | 2019-11-06 23:13:12 | 2019-11-06 23:13:12 |
| 152443 |                998 |       42998 |       32215 | ReviewResponseMap | 2019-11-06 23:22:15 | 2019-11-06 23:22:15 |
| 152444 |                998 |       42998 |       32135 | ReviewResponseMap | 2019-11-06 23:37:41 | 2019-11-06 23:37:41 |
| 152447 |                998 |       42998 |       32180 | ReviewResponseMap | 2019-11-07 00:02:01 | 2019-11-07 00:02:01 |
+--------+--------------------+-------------+-------------+-------------------+---------------------+---------------------+

mysql> select * from responses where map_id in (152442, 152443, 152444, 152447);
+--------+--------++---------------------+---------------------+-------------+-------+--------------+
| id     | map_id || created_at          | updated_at          | version_num | round | is_submitted |
+--------+--------++---------------------+---------------------+-------------+-------+--------------+
| 122551 | 152442 || 2019-11-06 23:13:26 | 2019-11-06 23:21:56 |        NULL |     1 |            1 |
| 122552 | 152443 || 2019-11-06 23:22:35 | 2019-11-06 23:37:22 |        NULL |     1 |            1 |
| 122553 | 152444 || 2019-11-06 23:37:45 | 2019-11-07 00:01:41 |        NULL |     1 |            1 |
| 122556 | 152447 || 2019-11-07 00:02:04 | 2019-11-07 00:18:05 |        NULL |     1 |            1 |
+--------+--------++---------------------+---------------------+-------------+-------+--------------+

mysql> select * from answers where response_id = 122551;
+---------+-------------+--------+-----------------------------------------------------------------+-------------+
| id      | question_id | answer | comments                                                        | response_id |
+---------+-------------+--------+-----------------------------------------------------------------+-------------+
| 1342175 |        6148 |      5 |                                                                 |      122551 |
| 1342176 |        6149 |      4 |                                                                 |      122551 |
| 1342177 |        6150 |      5 |                                                                 |      122551 |
| 1342178 |        6151 |      4 |                                                                 |      122551 |
| 1342179 |        6152 |      4 |                                                                 |      122551 |
| 1342180 |        6153 |   NULL | The author's work is relevt permission to view it.&nbsp; |      122551 |
| 1342181 |        6157 |   NULL |                                                                 |      122551 |
| 1342182 |        6155 |   NULL | NULL                                                            |      122551 |
+---------+-------------+--------+-----------------------------------------------------------------+-------------+

mysql> select * from answers where response_id = 122552;
+---------+-------------+--------+----------------------------------------------------+-------------+
| id      | question_id | answer | comments                                           | response_id |
+---------+-------------+--------+----------------------------------------------------+-------------+
| 1342183 |        6148 |      5 |                                                    |      122552 |
| 1342184 |        6149 |      5 |                                                    |      122552 |
| 1342185 |        6150 |      5 |                                                    |      122552 |
| 1342186 |        6151 |      5 |                                                    |      122552 |
| 1342187 |        6152 |      5 |                                                    |      122552 |
| 1342188 |        6153 |   NULL | The graphics and layout hehis lesson.&nbsp; |      122552 |
| 1342189 |        6157 |   NULL |                                                    |      122552 |
| 1342190 |        6155 |   NULL | NULL                                               |      122552 |
+---------+-------------+--------+----------------------------------------------------+-------------+

mysql> select * from answers where response_id = 122553;
+---------+-------------+--------+------------------------------------------------------------+-------------+
| id      | question_id | answer | comments                                                   | response_id |
+---------+-------------+--------+------------------------------------------------------------+-------------+
| 1342191 |        6148 |      5 |                                                            |      122553 |
| 1342192 |        6149 |      5 |                                                            |      122553 |
| 1342193 |        6150 |      5 |                                                            |      122553 |
| 1342194 |        6151 |      5 |                                                            |      122553 |
| 1342195 |        6152 |      4 |                                                            |      122553 |
| 1342196 |        6153 |   NULL | The lesson was insightful and tture teachers.&nbsp; |      122553 |
| 1342197 |        6157 |   NULL |                                                            |      122553 |
| 1342198 |        6155 |   NULL | NULL                                                       |      122553 |
+---------+-------------+--------+------------------------------------------------------------+-------------+

mysql> select * from answers where response_id = 122556;
+---------+-------------+--------+-----------------------------------------------------------------------------------+-------------+
| id      | question_id | answer | comments                                                                          | response_id |
+---------+-------------+--------+-----------------------------------------------------------------------------------+-------------+
| 1342215 |        6148 |      5 |                                                                                   |      122556 |
| 1342216 |        6149 |      4 |                                                                                   |      122556 |
| 1342217 |        6150 |      5 |                                                                                   |      122556 |
| 1342218 |        6151 |      4 |                                                                                   |      122556 |
| 1342219 |        6152 |      4 |                                                                                   |      122556 |
| 1342220 |        6153 |   NULL | This work is relevant because uld be equipped with that information.&nbsp; |      122556 |
| 1342221 |        6157 |   NULL |                                                                                   |      122556 |
| 1342222 |        6155 |   NULL | NULL                                                                              |      122556 |
+---------+-------------+--------+-----------------------------------------------------------------------------------+-------------+
`

**Comment by Saurabh110** [comment]
Could not reproduce
