### ISSUE TITLE
Student gets own submission to metareview

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#162]
The following happened for the Final Project assignment in CSC/ECE 517:

On Sun, Dec 4, 2011 at 10:13 PM, Sreepathi Prasanna ssreepa@ncsu.edu wrote:

```
Hello Professor,
When I selected a new meta review, I got our own project for metareview. Is this expected ? I thought we should be getting other project's for metareviewing ?
Regards,
 - Sreepathi
```

**Comment by efg** [comment]
This issue is of much lower priority now.  It should be aggregated with other metareview issues and added to a project on refactoring and testing metareviewing.

**Comment by ferryxo** [comment]
I'm not sure why this is wrong? shouldn't the author do the meta review? since they are the only people who can judge best if the review is helpful or not? or at least they should be more committed to provide  feedback to the reviewers

**Comment by efg** [comment]
No, a metareview is not author feedback (rejoinder).  Metareviews are
supposed to be done by disinterested third parties.

-Ed

**Comment by Saurabh110** [comment]
Loop on line 105 in [https://github.com/expertiza/expertiza/blob/master/app/models/assignment.rb](assignment.rb) prevents this.
