### ISSUE TITLE
Copying a copy of an assignment appears to fail

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1620]
If a copy of an assignment is itself copied, a notification says that it failed, but a copy is in fact inserted into the db.  See the description at "Our Recommendation for a Separate Issue" in http://wiki.expertiza.ncsu.edu/index.php/CSC/ECE_517_Fall_2019_-_E1959._Intelligent_copying_of_assignments_without_topics

**Comment by SaNPai23** [comment]
Changed the naming scheme for copied assignments to prevent this issue. The name of new assignment is set as 'Copy of <old assignment name>'. Now, if it already exists, it is set as 'Copy of <old assignment name> (1)'. Process is repeated with increasing integers till unique name is found.
