### ISSUE TITLE
Users are not made participants in an assignment if their account already exists

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1621]
Reported by E1962 team: If a user already exists in the system and appears in the csv file while importing participants, then the code only checks that the user exists and moves ahead. However, the user is not added as a participant on that assignment.

Participants are being added to the assignment only when user does not exist in the system already and user is newly getting created.

_I am surprised by this; I'm pretty sure I have imported such participants successfully many times._

**Comment by Saurabh110** [comment]
Fixed by commit #20edb13974f4fb0744d487d04eae396693cc8ba0
