### ISSUE TITLE
Hardcoded values for Question types when filling out questionnaire

### ISSUE THREAD

**Issue by ramlohith** [expertiza/expertiza#1669]
A hash map is being used currently to populate the type of questions in a questionnaire - such as criterion/dropdown/scale. If new type of questions are to be added, then the hash map has to be explicitly changed, and maintaining code will be difficult. 

 app/views/questionnaires/_questionnaire.html.erb - file has the hash map being referred to.

**Comment by Saurabh110** [comment]
This could be given as a project next semester.
