### ISSUE TITLE
Check for number of reviews is WRONG in a calibration assignment

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1671]
This occurred in trying to assign reviewers for Assignment 1006 (created by jkidd).

In this assignment, only two individuals had submitted.  Both of them were submitting work to serve as calibration exercises for the students.  All 84 students in the class were supposed to be assigned to review these two submissions.

Well, there is a check in the system that goes like this:

"You cannot set the number of reviews done by each student to be greater than or equal to total number of teams [or "participants" if it is an individual assignment]."

This seems like it should not cause trouble, because there are 84 participants and only 2 reviews to be done by each student.  But aha!  Behind the scenes, Expertiza creates "teams" for individual participants only when they click on "Your work" in preparation for submitting work.  The students are not submitting in this calibration assignment; they are only reviewing the two calibration exercises.  So, when reviewer assignment runs, there are only two "teams" (the 2 users who submitted the calibration exercises) and there are two reviews to be done by each student.  Two is greater than or equal to 2, and thus, the check prevents reviews from being assigned.

This check makes perfect sense for assignments for which each student submits work.  The number of reviews you are doing needs to be less than the number of submissions there are, because you are not allowed to review your own work.  It fails in situations where different people are submitting and reviewing, because in these cases, a student might indeed review all of the submissions.

So the check needs to be something like, "You cannot set the number of reviews done by each student to be greater than or equal to the number of submissions made by other participants."

**Comment by efg** [comment]
Related to #1683.

**Comment by Saurabh110** [comment]
According to [this](https://github.com/expertiza/expertiza/blob/master/app/controllers/review_mapping_controller.rb#L353) the above mentioned check is evaluated only if the assignment is not a calibrated assignment.

If the assignment is an individual assignment then the [code](https://github.com/expertiza/expertiza/blob/master/app/controllers/review_mapping_controller.rb#L340) creates teams.

If the assignment has teams then the review mapping should be done after all the particiants teams have selected their team, else some participants might remain unassigned to any submission.

If the instructor decides to assign reviews pre-submission then the check mentioned in the above last line of the above comment would fail. Instead the current [check](https://github.com/expertiza/expertiza/blob/master/app/controllers/review_mapping_controller.rb#L359) seems logical.
