### ISSUE TITLE
Remove dead methods from popup_controller.rb

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1673]
popup_controller.rb has 316 LoC and 9 methods.  The longest methods are not used, and could be removed:

* build_tone_analysis_heatmap # no calls except from testing code
* build_tone_analysis_report #  no calls except from testing code
* participants_popup  #  no calls except from testing code
* tone_analysis_chart_popup # no calls except from testing code

Of course, when these methods are removed, the corresponding tests should also be removed.

**Comment by efg** [comment]
Has this already been done by a Spring 2020 project?  Check.

**Comment by Saurabh110** [comment]
Methods  'build_tone_analysis_heatmap' and 'build_tone_analysis_report' are called by method ['view_review_scores_popup'](https://github.com/expertiza/expertiza/blob/master/app/controllers/popup_controller.rb#L62) which is called from [review_report partial](https://github.com/expertiza/expertiza/blob/master/app/views/reports/_review_report.html.erb#L64).

Remaining two methods are removed in the following commit.
