### ISSUE TITLE
Feature Request - To be able to attach images on Expertiza review comment box, just like how Piazza allows you to do

### ISSUE THREAD

**Issue by abhishekupadhyaya** [expertiza/expertiza#1675]
While providing review comments, I wish there was a way to attach images on Expertiza review comment box, just like how Piazza or other applications allows you to do. That way, we could attach screenshot of the features/errors that we saw while reviewing someone else's application for assignments.

Currently, we can only add URL links or video in comment box as shown below:
<img width="1242" alt="Screen Shot 2020-02-24 at 6 16 37 PM" src="https://user-images.githubusercontent.com/8761854/75199740-dfebad80-5731-11ea-921c-47e6d33b5d0a.png">
<img width="1221" alt="Screen Shot 2020-02-24 at 6 16 45 PM" src="https://user-images.githubusercontent.com/8761854/75199744-e24e0780-5731-11ea-9dbf-000b60cfcc75.png">

Types of attachments allowed on Piazza posts/comments:
<img width="953" alt="Screen Shot 2020-02-24 at 6 17 44 PM" src="https://user-images.githubusercontent.com/8761854/75199798-0c9fc500-5732-11ea-9924-855a775de9d4.png">

**Comment by efg** [comment]
Implement like the File Upload rubric type.

**Comment by johnbumgardner** [comment]
this is implemented
