### ISSUE TITLE
max_label and min_label switched in rubric creation!

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1678]
When viewing a rubric, the min_label precedes the max_label:

![image](https://user-images.githubusercontent.com/127445/75618658-81fb0380-5b3f-11ea-96fd-e7f1493f2fac.png)

whereas when editing a rubric, the max_label precedes the min_label:

![image](https://user-images.githubusercontent.com/127445/75618651-64c63500-5b3f-11ea-967d-96efc4f14d18.png)

This is totally illogical!  Whoever created this, what could they have been thinking?!  Putting the max_label before the min_label is very likely to confuse the user into getting the scale backwards.  The edit template needs to be fixed!

**Comment by Saurabh110** [comment]
Fixed in d018b0ec937b3ef31e3df236f0da843083b8c8ef
