### ISSUE TITLE
Error creating a new user with duplicate credentials (user email and ID)

### ISSUE THREAD

**Issue by sppapalkar** [expertiza/expertiza#1719]
![image](https://user-images.githubusercontent.com/60016007/78900746-465c2f00-7a45-11ea-97bd-3317272312ac.png)

**Comment by SaNPai23** [comment]
Issue caused due to instance variable 'rolename' not being populated when save method for user fails in users#create. Changed render_action 'new' to redirect_to 'new' with a 'Student' parameter as the 'new' method populates 'rolename' correctly.
