### ISSUE TITLE
Travis Build failure on branch for DB migration files

### ISSUE THREAD

**Issue by khotAyush** [expertiza/expertiza#1732]
Travis Build on branch failing on rake db:setup with error 'Pending Migrations'
https://travis-ci.org/github/expertiza/expertiza/jobs/677970821

**Comment by khotAyush** [comment]
Current Workaround: Check-in schema.rb to prevent build failure

**Comment by Saurabh110** [comment]
Setting up travis to run on migrations causes a lot more time to build the database than to run on the schema.rb
(db:migrate takes around 1-2 minutes while db:setup takes on 10-15 seconds.)

So every pull request which make changes to the database schema must include schema.rb
