### ISSUE TITLE
Hide/show tags in reviews duplicated and unused

### ISSUE THREAD

**Issue by belld19233** [expertiza/expertiza#1733]
As a student, looking at your score for an assignment also shows review tagging options. This can be hidden via the first "hide tags" option under an assignment's first round.

![image](https://user-images.githubusercontent.com/25886486/80318391-ccaf9980-87d7-11ea-80f9-548d7a2f9be2.png)

When a second round is introduced, the same setup appears:
![image](https://user-images.githubusercontent.com/25886486/80318414-f7015700-87d7-11ea-95ba-b974e6149bfd.png)

However, you cannot use the second round's "hide tagging" to display/hide tagging for the second round. Instead, the first occurrence of hide/show tags must be used for the second round.

Ideally, either one button for showing/hiding tagging should exist or each appearance should be limited to its own table.

**Comment by Saurabh110** [comment]
Fixed in commit 54520de
