### ISSUE TITLE
Error in creating new user

### ISSUE THREAD

**Issue by adityag3** [expertiza/expertiza#1739]
Steps to reach the issue : 
1) Visit expertiza
2) Login_as 'admin_user'
3) Visit list of users
4) Click New User link
5) Fill user_name with 'teststudent'
6) Fill user_fullname with 'test student'
7) Fill user_email with 'test@student.com'
8) Check checkbox to send email to user on review
9) Click 'Create' button.
![image](https://user-images.githubusercontent.com/12672880/84656720-22074d80-aee1-11ea-904b-828f6d0c0d10.png)

**Comment by adityag3** [comment]
https://github.com/expertiza/expertiza/pull/1736

**Comment by Saurabh110** [comment]
Working on the test server, as well as the main server.
