### ISSUE TITLE
Check for true_false_questions? just checks whether there is at least one checkbox question!

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1747]
See questionnaire.rb

 # Does this questionnaire contain true/false questions?
  def true_false_questions?
    questions.each {|question| return true if question.type == "Checkbox" }
    false
  end

The code may not be incorrect, but the method name is certainly misleading.

**Comment by yangsong8** [comment]
should be "is_any_true_false_questions?" or "contains_true_false_questions?"
