### ISSUE TITLE
In a quiz-enabled assignment, Expertiza is saying that work hasn't been submitted when it has!

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1751]
Look at assignment 785.  It "has quiz".  But when I change the deadline to put myself in the review period, I can select topics for review (e.g., Platform9 Managed OpenStack or Literate Programming.  But when I go to review them, I am told that they haven't been submitted, when in fact they have been.

I should be able to review these, even if I have asked late.  The system shouldn't tell me they haven't been submitted.

Thanks,

**Comment by johnbumgardner** [comment]
<% if @num_reviews_in_progress >= Assignment.max_outstanding_reviews %>
              <br><br>
              <span>Note: You can't have more than 2 outstanding reviews. You must complete one of your outstanding reviews before selecting another.</span>

Needs to be updated

**Comment by johnbumgardner** [comment]
./app/views/shared/responses/_response_actions.html.erb
Seems to be offending code

**Comment by efg** [comment]
Specifically, it needs to be "Note: You can't have more than " + max_outstanding_reviews + " reviews.  You must complete ..."
