### ISSUE TITLE
view_publishing_rights --> view_copyright_grants ... incompletely implemented

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1755]
"Publishing rights" should be changed to "Copyright grants", because it means that a student has allowed the instructor to use his/her work later on.

The code is incompletely implemented, because currently there does not seem to be any way for a student to grant permission.

**Comment by Saurabh110** [comment]
![image](https://user-images.githubusercontent.com/54721827/91485237-872fd580-e878-11ea-9643-46d89cc2feb3.png)
The link in the above screenshot works correctly.
