### ISSUE TITLE
Review disabling still doesn't work during a review period

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1759]
While I was deleting reviews that used the wrong rubric (my mistake!) I simply turned review permission off during the current review period.  Alas, the "Others' work" option was still clickable, and two students started new reviews (which I then had to delete as well).

If review permission is set to "No", reviews should not be able to be done!  Mechanism and policy are conflated in the code, and this needs to be fixed.

**Comment by Saurabh110** [comment]
The check works correctly. To disable the Others' work option, you should turn review permissions as well as meta-review permissions off too.
Please reopen if the issue still persists.
