### ISSUE TITLE
Changing deadlines no longer works reliably

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1799]
For OSS Project & Documentation, assignment 1028, I was unable to change the deadlines via the Due dates tab of the UI!

Whenever I would change the deadlines, as soon as I did a Save, the Round 2 deadlines would revert to what they were before.  Finally I selected, then unselected, "Name and description URL vary by round" and then the change was saved!

I don't know what is wrong, but obviously not all deadlines are saved when I click "Save".

**Comment by Saurabh110** [comment]
There were multiple entries in the db for the same deadline. Similar to #1813
