### ISSUE TITLE
TA method assumes that a TA only TAs for one instructor

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1812]
The self.get_my_instructor method in ta.rb assumes that a particular TA is associated with only one instructor.  The first time someone TAs for two different courses with two different instructors in Expertiza, the method will fail.

  # This method is potentially problematic: it assumes one TA only help teach one course.
  # This method only returns the instructor_id for the 1st course that this user help teach.  -Yang Oct. 05 2015
  def self.get_my_instructor(user_id)
    course_id = TaMapping.get_course_id(user_id)
    Course.find(course_id).instructor_id
  end

**Comment by Saurabh110** [comment]
There is another method 'get_my_instructors' which has been used to replace the old method.
