### ISSUE TITLE
Error thrown when you try and open “Bookmark Rating” in the “Questionnaires”

### ISSUE THREAD

**Issue by ItsThatGuySudhanshu** [expertiza/expertiza#1837]
If you go to questionnaires under the Manage tab, and click on the plus sign next to bookmark rating, the page throws an error.

Attaching the image of the error thrown:

[https://docs.google.com/document/d/15HzIS5Zyy9XZUV1c8gFKNS0jv5jGB1RE_4JCncJBLEI/edit?usp=sharing](url)

**Comment by johnbumgardner** [comment]
@Saurabh110 check this PR out
