### ISSUE TITLE
"Sample submissions" shows up in all assignments

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1865]
On the student site, the "Sample submissions (View sample work submitted by other participants/teams)" shows up on each assignment, whether or not sample submissions are in use.  This must be fixed before anyone uses the system, so we don't confuse users!

**Comment by efg** [comment]
And, students get asked whether their submission can be shown to others all the time, not just when sample submissions are in use.

**Comment by johnbumgardner** [comment]
This has been removed in the beta branch.
