### ISSUE TITLE
Unclickable "Tone analysis" appears when one tries to review

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1868]
In doing a review for the Beta test assignment , "Tone analysis" appears beneath each question.  After the review is saved, this is where the comment appears colored a particular color, based on how positive it is.  It is a confusing UI, because at the start, it just says "Tone analysis" with no explanation.  Nothing should appear until the review is saved, then the _original review_ text should be colored in the edit box.

**Comment by johnbumgardner** [comment]
@efg could you provide a screenshot of this? im having trouble replicating the bug.

**Comment by johnbumgardner** [comment]
![image](https://user-images.githubusercontent.com/38589044/123165649-7fae6e00-d442-11eb-9da8-4e27d970d501.png)

**Comment by efg** [comment]
Yes, this is confusing.  The phrase "Tone analysis" should appear in the same box as the text, and somewhere it should have "Positive" in green and "Negative" in red.
