### ISSUE TITLE
NoMethodError in StudentTaskController#list

### ISSUE THREAD

**Issue by Swagtiger28** [expertiza/expertiza#1870]
My account was someone else's(Praveen Wagle) account. Information may have been lost, causing this error to occur. Here is a screenshot:
![image](https://user-images.githubusercontent.com/45515938/103949726-b3ead800-5109-11eb-9d7e-c523e43e991c.png)

**Comment by johnbumgardner** [comment]
@Swagtiger28 would you mind sharing username you were on so i can impersonate to replicate bug
