### ISSUE TITLE
Keyword "apradee" shows up automatically when creating a handle for current issue

### ISSUE THREAD

**Issue by kpiryani10** [expertiza/expertiza#1873]
Click on Assignments and then click Wiki 1. There should be an option to “change a handle”, so click that and it should lead to the tab titled Create or Change Handle for Current Assignment

![apradee](https://user-images.githubusercontent.com/61096975/123162054-26444000-d43e-11eb-89f6-53cca4737fa4.png)

http://152.46.17.170:8080/student_task/view?id=86

**Comment by kpiryani10** [comment]
Click on Assignments and then click Wiki 1. There should be an option to “change a handle”, so click that and it should lead to the tab titled Create or Change Handle for Current Assignment

![apradee](https://user-images.githubusercontent.com/61096975/123162054-26444000-d43e-11eb-89f6-53cca4737fa4.png)

http://152.46.17.170:8080/student_task/view?id=86

**Comment by johnbumgardner** [comment]
I think this is standard functionality
