### ISSUE TITLE
Need a way for an instructor to sign students up for topics

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#188]
An instructor can add and remove students from teams.  But an instructor cannot sign students up for topics without impersonating them.  This is an important lack, because often signups get messed up due to mistakes or misinterpretation.  It should be possible for the instructor to sign a student or team up for a topic, or to drop a topic for a student or team.

Actually, implementing this only for teams would be good enough, because individual assignments are going to be changed to team assgts. w/a team size of 1.

**Comment by yangsong8** [comment]
Implemented by E1714.
