### ISSUE TITLE
Double-clicking on a signup sheet signs you up twice!

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#193]
If a user who has not yet created a team tries to sign up for a topic, and hits the green check mark twice before the system responds, then it seems that
- two teams are created for the user,
- both teams are signed up for the topic, and
- if there was only one slot remaining for the topic, the number of remaining slots is now -1.

This can easily happen when Expertiza is slow.

I'm not sure what's the best way to fix it, but one thing that might work is to lock other users out of changing the number of slots until the first transaction is finished.

**Comment by yangsong8** [comment]
Tested on June 14, 2017 and this is fixed.

![image](https://user-images.githubusercontent.com/4420550/27145442-db4966be-5103-11e7-9ce5-76cd18f55688.png)
