### ISSUE TITLE
Wrong error message if you try to add an existing participant

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#194]
If a particular user is already a participant in an assignment & you try to add him/her again, you get this message:

User [[username]] does not exist. Would you like to create this user?

The message should be something like,

User [[username]] is already a participant in this assignment.

**Comment by efg** [comment]
Currently the message is, "User ... does not exist or has already been added."

It would be really good if the code figured out which of the two was actually the case.

**Comment by yangsong8** [comment]
Chris fixed this.
