### ISSUE TITLE
Abstraction for Quality Filtering

### ISSUE THREAD

**Issue by johnbumgardner** [expertiza/expertiza#1943]
Right now, the way we tag outliers is in code in tag_prompt_deployment, as we’re only checking for the length of the comment being greater than some set threshold.

![image](https://user-images.githubusercontent.com/38589044/115584110-841aa700-a298-11eb-85f4-6c9d51268887.png)

What makes sense to me is creating a class QualityFiltering or something named like that, and have when you set up an assignment, you can attach subclasses of answer quality filtering to an assignment, so something like

```Ruby 
class OutlierFiltering < QualityFiltering # This is your where the tagging result is different from their teammates
```

Similarly, move the threshold quality to something similar

```Ruby 
class ThresholdFiltering < QualityFiltering # This is the current algorithm that filters by length.
```

Then, the line where answers are filtered will resemble something like this

```Ruby
assignment.quality_filtering.each do |filter|
	answers = filter.apply_filter(answers)
end
```

If we approach the problem in this way, we can continue to add increasingly sophisticated quality control without needing to redesign the TagPromptDeployment every time.

**Comment by efg** [comment]
This is the same as #1830.
