### ISSUE TITLE
If a signup sheet, team should have to sign up before submitting

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#195]
In an assignment with a signup sheet, when a user submits, the system does not check whether the user is signed up for a topic.  It should.  Users should not be able to submit without choosing a topic.  Sometimes users forget to sign up, and then their submissions can't be reviewed, because the reviewer has to choose a topic to review on, and thus can't review submissions that are not associated with a topic.

**Comment by yangsong8** [comment]
Students cannot click on "Your work" if they do not have a topic first (for assignments w/ topics.)
