### ISSUE TITLE
Seemingly random failure on Travis

### ISSUE THREAD

**Issue by johnbumgardner** [expertiza/expertiza#1955]
Every few builds, I get this error. Might cause some devs pushing code to think they caused a problem when they in fact didnt.

![image](https://user-images.githubusercontent.com/38589044/116580174-1c400e00-a8e1-11eb-9211-39f2751959fb.png)

**Comment by johnbumgardner** [comment]
Running locally, I get two failures

![image](https://user-images.githubusercontent.com/38589044/116580713-a1c3be00-a8e1-11eb-80ac-0b99d6fa8ba3.png)

**Comment by efg** [comment]
It is the same test(s) that fail every time something fails.

**Comment by johnbumgardner** [comment]
airbrake resolved for now
