### ISSUE TITLE
Assignment should not ask to copy without topics if there are no topics!

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1958]
Another bonehead UI decision by a team that thinks that the world revolves around their project ...

When I go to copy an assignment, I am greeted by a page that asks,

Select the desired choice and copy the assignment
 copy without topics
 copy with topics
 copy with topics and teams

There are so many things wrong with this ...

- the assignment does not have topics, so I should not be asked whether I want to copy "with topics".
- the three choices omit, "copy with teams" (but not topics), though
- it does not make sense to "copy with teams", since (i) teams are always specific to an assignment; one could choose to inherit teams from the course, but that's a choice on the "Create teams" page, (ii) most of the time, the assignment is being copied to a different semester, where you can't copy the teams because the students are different
- the wording is clumsy (why do we have a 2-line title, why not just "Choose option for copy"?

This page should appear only if the assignment has topics, and then all it needs to ask is "Copy with topics?"  A checkbox would be more appropriate than a radio button.

**Comment by efg** [comment]
Not only that ... this page has changed the functionality of copy.  Now, it just saves the assignment instead of redirecting to the Editing assignment page.  It doesn't give me the option anymore of choosing the course and the title of the assignment.

This must be fixed!

**Comment by johnbumgardner** [comment]
On beta, when I click copy
![image](https://user-images.githubusercontent.com/38589044/116735630-cc367980-a9bc-11eb-88e9-0c03afc7fd5a.png)
It redirects me to the editing assignment page. 
![image](https://user-images.githubusercontent.com/38589044/116735319-53cfb880-a9bc-11eb-975e-5524a51b7995.png)
Is this issue you're referring to on master branch? @efg

**Comment by johnbumgardner** [comment]
This has all been removed in the beta branch.
