### ISSUE TITLE
Meta-reviews do not show the review to be reviewed

### ISSUE THREAD

**Issue by sterlingalexander** [expertiza/expertiza#198]
Hi,

I am currently participating in CSC 506 and attempting to do meta-reviews.  When I am assigned the meta-review, the original review I'm supposed to critique is not shown, only the link to the wiki article and the review rubric.    There are also reports in Piazza (#195) that others are experiencing the exact same issue.

**Comment by yangsong8** [comment]
We think it should be fixed. Will find an assignment w/ meta reivews and check later.

**Comment by efg** [comment]
E1774, OSS Project Pink, was merged.
However, currently, it does not work to begin a new metareview, because someone deleted a needed partial.

**Comment by Saurabh110** [comment]
Fixed in commit c25aa3b1d5ee7780119545d4134475f8a88820ea
