### ISSUE TITLE
For individual assignments, authors' names appear even in anonymized view.

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#1996]
Check out https://expertiza.ncsu.edu/reports/response_report?class=form-inline&id=1051

Here, the submitters are individuals, so Expertiza changes the team name to the submitter's name.  Anonymized view should change the names to "Student nnnn" as in any other situation where an individual's name would be displayed.

**Comment by johnbumgardner** [comment]
How currently is anonymized view handled? Would you mind providing greater explanation for what this code is doing.

```Ruby
def set_anonymized_view
    anonymized_view_starter_ips = $redis.get('anonymized_view_starter_ips') || ''
    session[:ip] = request.remote_ip
    if anonymized_view_starter_ips.include? session[:ip]
      anonymized_view_starter_ips.delete!(" #{session[:ip]}")
    else
      anonymized_view_starter_ips += " #{session[:ip]}"
    end
    $redis.set('anonymized_view_starter_ips', anonymized_view_starter_ips)
    redirect_to :back
  end
```

**Comment by johnbumgardner** [comment]
How currently is anonymized view handled? Would you mind providing greater explanation for what this code is doing.

```Ruby
def set_anonymized_view
    anonymized_view_starter_ips = $redis.get('anonymized_view_starter_ips') || ''
    session[:ip] = request.remote_ip
    if anonymized_view_starter_ips.include? session[:ip]
      anonymized_view_starter_ips.delete!(" #{session[:ip]}")
    else
      anonymized_view_starter_ips += " #{session[:ip]}"
    end
    $redis.set('anonymized_view_starter_ips', anonymized_view_starter_ips)
    redirect_to :back
  end
```

**Comment by johnbumgardner** [comment]
![image](https://user-images.githubusercontent.com/38589044/123691827-12288600-d824-11eb-813a-6fd744f0fe0f.png)
Another issue with anonymized view.

**Comment by johnbumgardner** [comment]
Fixed in beta
