### ISSUE TITLE
When creating an assignment, the UI should prompt user to add participants

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#2018]
It is too easy to create an assignment and then forget to add the participants.  If you forget, students will not see the assignment.

So, when an assignment that does not have participants is saved, the UI should prompt for whether the user wants to add participants (and if so, redirect to the Add participants page).  If the assignment is part of a Course, and the Course has CourseParticipants, then the UI should ask if the user wants to add all Course Participants to the Assignment.

**Comment by johnbumgardner** [comment]
Fixed in beta!
