### ISSUE TITLE
UI: "Add" button in creating questionnaire needs a new color

### ISSUE THREAD

**Issue by YunkaiXiao** [expertiza/expertiza#2042]
Log in as a TA or instructor, manage questionnaire, edit or create one

![image](https://user-images.githubusercontent.com/7957720/134229579-c3aa5964-2e1e-411c-9ffc-ec4f7d9fff74.png)

The add button here looks like a textbox instead of a button, this is very confusing and could be made the same color as the save button below

**Comment by johnbumgardner** [comment]
Issue now fixed in Beta
