### ISSUE TITLE
Bug: Cannot remove tag prompt when editing assignment

### ISSUE THREAD

**Issue by YunkaiXiao** [expertiza/expertiza#2043]
Log in as instructor or TA, edit an assignment and move to rubrics tab

![image](https://user-images.githubusercontent.com/7957720/134235028-7e99556c-1d5d-4f88-9bb2-7311e0fe981e.png)

clicking on the +tag prompt+ does add tag prompt to the review questionnaire, while -tag prompt- does not do anything

**Comment by johnbumgardner** [comment]
Seems to be an issue in app/views/assignments/edit/_rubric.html.erb in the removeLastTagPromptDropdown function.

**Comment by divyang02** [comment]
@johnbumgardner I was able to resolve the UI issue, but it seems that the "Save" button is also not working here. When I remove the tag prompt from the UI and hit the "Save" button I was expecting that Questionaire will be updated accordingly, but it's not fetching the updated value from the UI. I will try to look into it. 
cc - @efg

**Comment by johnbumgardner** [comment]
@divyang02 that sounds great. Let me know when you make a PR and I will look it over and get it merged in!

**Comment by johnbumgardner** [comment]
#2172 fixes this issue on beta. closing this
