### ISSUE TITLE
Can't add new tags

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#2052]
I needed to add a "Contains examples" tag for CSC 517 Program 2.  It is impossible to add a tag (the save button is missing), so I had to edit the existing "Mitigation" tag to make it "Contains examples?"  This is a new issue, because I have added several tags from the UI in the past.

**Comment by divyang02** [comment]
As discussed, this functionality is currently working but the UI is not intuitive enough. Instead of '+' symbol for adding a new Tag Prompt, it should be changed to the 'Save' button when creating a new Tag Prompt from the pop-up menu. 
cc - @efg

**Comment by johnbumgardner** [comment]
@divyang02 what is the status on this?

**Comment by johnbumgardner** [comment]
closing this as this is working
