### ISSUE TITLE
Summary report shows no teams

### ISSUE THREAD

**Issue by nnhimes** [expertiza/expertiza#2067]
Viewing the summary report for a badge assignment we created shows no teams created, even after the team creation, submission, and review deadlines

**Comment by nnhimes** [comment]
Clicking view scores shows this summary report. So grades cannot be seen

**Comment by johnbumgardner** [comment]
this is related to how we loop over teams I believe. we go 0 upto teams.length-1 so we cut off a team, can you verify this. this should be resolved by #2418
