### ISSUE TITLE
BUG Beta: cannot impersonate student

### ISSUE THREAD

**Issue by YunkaiXiao** [expertiza/expertiza#2091]
![image](https://user-images.githubusercontent.com/7957720/137387194-02411526-6922-4f2d-8d4f-7ea07ef363cb.png)

**Comment by johnbumgardner** [comment]
To impersonate student11, you must either be their TA, a super administrator, or recursively their parent. 

If you are trying to impersonate this user as instructor6, you neither a superadmin, a TA, nor a parent, as the parent of student11 is super_administrator2.

This is correctly functioning. As such, I am closing this issue.
