### ISSUE TITLE
Error after someone picks all but one available review

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#213]
From Dan Eckert, dcecker2@ncsu.edu

It appears that once you've reviewed all but one of the topics available, the Reviews page goes back to showing all of the topics as available in the selection list but then gives you an error whether you pick one or click "I don't care which topic I review" so it's impossible to do the last review unless you remember which topic was left.  Also, some reviews appear blank when selected and when listed in the metareviews section.

**Comment by yangsong8** [comment]
Should be fixed.
