### ISSUE TITLE
Same author feedback given to multiple reviewers

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#215]
Arvind Chandrasekar achandr6@ncsu.edu:

I had a total of 7 reviewers [for Wiki 1a] and I submitted a feedback for my Reviewer No. 3 and the same review has been given to all reviewers from 4 to 7. I found this out when instead of a "Give feedback" link for all the rest of the reviewers, these reviewers had a "view" or edit you feedback" links. When I click "view" the feedback I gave for the Reviewer No. 3 is displayed. Is this a bug in Expertiza?

**Comment by yangsong8** [comment]
Have not been heard about this bug for a long time.
