### ISSUE TITLE
Viewing Survey Responses on Assignment Crashes

### ISSUE THREAD

**Issue by nnhimes** [expertiza/expertiza#2184]
When editing an assignment, clicking the Etc tab, and then "View survey responses" crashes Expertiza. 

This screenshot is for the OSS Project & Documentation assignment.

![image](https://user-images.githubusercontent.com/41524135/149679205-3a6b3302-e964-40d2-ace8-1c06c2b9fff8.png)

Could be rerouted if no survey deployment found.

**Comment by johnbumgardner** [comment]
I think the best course of action is removing these views for now

**Comment by nnhimes** [comment]
Going to try and reroute it if its simple enough
