### ISSUE TITLE
Should be a way to change to/from Student view

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#22]
Most systems used for classwork allow instructors, admins., etc. to act as students.  In order to do so, they must "Switch to student view."  In Expertiza, admins can act as students too, but they do so by using different pull-down menus.  This is potentially confusing, especially for Assignments, which appear both in the admin and student menus,

**Comment by efg** [comment]
This should be as simple as changing the menus that are available to the instructor.

**Comment by efg** [comment]
This has been done in E1803, but we have not yet decided whether to merge this project.

**Comment by Saurabh110** [comment]
Fixed in the beta branch
