### ISSUE TITLE
Race condition in assigning directory numbers?

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#220]
The following (2 teams having the same directory number) suggests there may be a race condition in assigning directory numbers:

Hi Dr. Gehringer, the following students have the directory number 32.

(from the participants table)
+-------+----------+-----------+---------------+
| id    | handle   | parent_id | directory_num |
+-------+----------+-----------+---------------+
| 18981 | amendir2 |       534 |            32 |
| 18996 | bnshah   |       534 |            32 |
| 18997 | bsampat2 |       534 |            32 |
| 19029 | mmurali2 |       534 |            32 |
| 19030 | mprabha  |       534 |            32 |
| 19054 | pvasude  |       534 |            32 |
+-------+----------+-----------+---------------+
6 rows in set (0.06 sec)

I think bsampat2, mmurali2 and pvasude are on one team and amendir2, bnshah and mprabha on the other. The latter's files are being displayed on the former's your work page.

**Comment by yangsong8** [comment]
the dir_num is moved to the teams table.
