### ISSUE TITLE
Error in View scores on Program 1: Backchannel app

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#221]
When I do a "View report" on Program 1: Backchannel app, after waiting a long time (~ 15 min.), this error occurs:

 NoMethodError in GradesController#view

undefined method `map' for nil:NilClass

RAILS_ROOT: /local/rails/expertiza/releases/20120920052733
Application Trace | Framework Trace | Full Trace

/local/rails/expertiza/releases/20120920052733/app/models/response_map.rb:33:in `get_assessments_for'
/local/rails/expertiza/releases/20120920052733/app/models/response_map.rb:33:in `sort!'
/local/rails/expertiza/releases/20120920052733/app/models/response_map.rb:33:in `get_assessments_for'
/local/rails/expertiza/releases/20120920052733/app/models/assignment_participant.rb:142:in `get_reviews'
/local/rails/expertiza/releases/20120920052733/app/models/review_questionnaire.rb:11:in `get_assessments_for'
/local/rails/expertiza/releases/20120920052733/app/models/assignment.rb:229:in `get_scores'
/local/rails/expertiza/releases/20120920052733/app/models/assignment.rb:226:in `get_scores'
/local/rails/expertiza/releases/20120920052733/app/models/assignment.rb:222:in `get_scores'
/local/rails/expertiza/releases/20120920052733/app/controllers/grades_controller.rb:17:in `view'

Request

Parameters:

{"id"=>"534"}

Show session dump

**Comment by yangsong8** [comment]
Tested, this page works
