### ISSUE TITLE
When someone creates a duplicate account, they should be warned!

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#2219]
If someone already has an account and you create a new account for them, then the disambiguation algorithm will be invoked, and the new account will be generated with a username that is the same as the user’s email address.

The algorithm works correctly, but there should be a flash notification that the username is **not** what you specified when you created the account!  Instead, the change is made silently, leading people to think there is something wrong with Expertiza.

**Comment by johnbumgardner** [comment]
Add a flash in users_controllers.rb in the create function. 
<img width="994" alt="image" src="https://user-images.githubusercontent.com/38589044/152012190-e5ba0b8e-4b57-40b8-8821-a10ab1b7536f.png">

**Comment by johnbumgardner** [comment]
Fixed
