### ISSUE TITLE
create_approved_user method in account_request_controller.rb should be refactored

### ISSUE THREAD

**Issue by namanshrimali** [expertiza/expertiza#2267]
The create_approved_user method in account_request_controller.rb should be refactored. The test case for the same are also very misleading and should be refactored as well.
Current failures due to introduction of strong parameters and rails 5.1 upgrade: 
rspec ./spec/controllers/account_request_controller_spec.rb:68 # AccountRequestController#create_approved_user the input status is Rejected
rspec ./spec/controllers/account_request_controller_spec.rb:34 # AccountRequestController#create_approved_user the input status is nil and original status is nil
rspec ./spec/controllers/account_request_controller_spec.rb:44 # AccountRequestController#create_approved_user the input status is Approved
rspec ./spec/controllers/account_request_controller_spec.rb:56 # AccountRequestController#create_approved_user the input status is Approved but save fails
rspec ./spec/controllers/account_request_controller_spec.rb:78 # AccountRequestController#create_approved_user the input status is Rejected but update_colums fails

**Comment by johnbumgardner** [comment]
@namanshrimali please use the rails5 label when labelling these issues created from the migration to rails 5.
