### ISSUE TITLE
Replace expertiza redirect_back with default rails solution

### ISSUE THREAD

**Issue by namanshrimali** [expertiza/expertiza#2270]
The entire application has incorrectly implemented `redirect_back`. Rails 5.1 has officially introduced redirect_back, so expertiza's implementation has to be removed, along with the places it is being used has to be updated with default rails solution.

**Comment by johnbumgardner** [comment]
oh thank goodness because our implementation is barely functional

**Comment by namanshrimali** [comment]
Fixed !
