### ISSUE TITLE
view_review_scores summary lists items out of order

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#2283]
In the review report, the summary review lists items out of order.

For example, items in Program 2, Spring 2022 formative are as follows:

<html>
<body>

The Admin class possesses all the required attributes | Scale | 1 | (Strongly disagree) 0 to 5 (Strongly agree)
-- | -- | -- | --
Please add comments to justify your rating. | TextField |   | —
The Course class possesses all the required attributes | Scale | 1 | (Strongly disagree) 0 to 5 (Strongly agree)
Please add comments to justify your rating. | TextField |   | —
The Instructor class possesses all the required attributes | Scale | 1 | (Strongly disagree) 0 to 5 (Strongly agree)
Please add comments to justify your rating.

</body>
</html>

In the summary view, the Textfield items are collected together, the Scale items are collected together, etc., which is badly out of order and makes it very hard to read.  This needs to be fixed!

**Comment by johnbumgardner** [comment]
<img width="1642" alt="image" src="https://user-images.githubusercontent.com/38589044/156009158-413aa836-b98f-443a-b405-b370faeb63c4.png">

This really isnt a problem in beta. Since we're surely migrating to beta, I think this is pretty low priority.
