### ISSUE TITLE
uninitialized constant UpdateParticipantTypes::CoursesUsers Issue

### ISSUE THREAD

**Issue by LukeMccon** [expertiza/expertiza#2294]
I'm running into this issue after running `rake db:migrate` on a fresh copy of the scrubbed database.
I believe it is trying to use the `CoursesUsers` model that does not exist with `CoursesUsers.all`

Stack Trace:
```
Caused by:
NameError: uninitialized constant UpdateParticipantTypes::CoursesUsers
/app/db/migrate/067_update_participant_types.rb:25:in `up'
...
Tasks: TOP => db:migrate
```

Relevant portion of the migration
```
course_users = CoursesUsers.all
    course_users.each do |user|
      CourseParticipant.create(user_id: user.user_id, parent_id: user.course_id)
    end
```

Seeing this on the latest version of beta

**Comment by johnbumgardner** [comment]
im running migration locally. try this file

https://drive.google.com/file/d/1fuTNtFlt2MLfSwadD_vqKNQnhvhGwmdt/view?usp=sharing
