### ISSUE TITLE
Import of course participants not working, header line suspected

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#2317]
The following file could not be imported into Expertiza.  It gives a message saying there is the wrong number of fields in a line.

username,Full Name ,EMAIL address
MANCH002,"MALIA ANCHETA","MANCH002@ODU.EDU",
SYOUN011,"SAMANTHA YOUNG","SYOUN011@ODU.EDU",
VSANT002,"Victoria SANTANA","VSANT002@ODU.EDU",
AWENG002,"ELEANOR JONES","AWENG002@ODU.EDU",
TMITC027,"Hardy MITCHELL","TMITC027@ODU.EDU",
PSTIL001,"PHILIP STILES","PSTIL001@ODU.EDU",
BRODR009,"BRITTANY RODRIGUEZ","BRODR009@ODU.EDU",
REDGE001,"Rachel EDGE","REDGE001@ODU.EDU",
IPOWE002,"IVYLYNN POWELL","IPOWE002@ODU.EDU",
DSHER008,"DELANEY SHERIDAN","DSHER008@ODU.EDU",
DMANN006,"DEANA MANNING","DMANN006@ODU.EDU",
MHARR054,"Mikayla HARRISON","MHARR054@ODU.EDU",
NSHEP004,"Noah SHEPHERD","NSHEP004@ODU.EDU",
SLEWI011,"SAMI LEWIS","SLEWI011@ODU.EDU",
FDUTC001,"Faith DUTCH","FDUTC001@ODU.EDU",
SWEBB014,"SAVANNAH WEBB","SWEBB014@ODU.EDU",
ADEVI005,"ASHLEY DEVINNEY","ADEVI005@ODU.EDU",
TSMIT079,"TESSA SMITH","TSMIT079@ODU.EDU",
TCHAT002,"Tjura CHATMAN","TCHAT002@ODU.EDU",
KSTOT001,"katie STOTTLEMYER","KSTOT001@ODU.EDU",
RPHEL001,"RORI PHELPS","RPHEL001@ODU.EDU",
AKIRT001,"ALISHA KIRTLEY","AKIRT001@ODU.EDU",
ABERE004,"AIDAN BERENS","ABERE004@ODU.EDU",
HSCAR001,"HANNAH SCARBROUGH","HSCAR001@ODU.EDU",
JCREW009,"Jaya CREWS","JCREW009@ODU.EDU",
LMUNO004,"Logan MUNOZ-LAWRENCE","LMUNO004@ODU.EDU",
HBUSO001,"HANNAH BUSONE","HBUSO001@ODU.EDU",

Since I can import files that look like this _without_ a header line, I suspect that some code to process header lines has a bug.

**Comment by johnbumgardner** [comment]
yes this issue is related to the database column for what we colloquially refer to as username.

in expertiza, this is just called name. it expects that in the header.

i added a note in the UI on beta that the header name is expected instead
