### ISSUE TITLE
Institution cannot be updated from the profile

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#2361]
Jennifer Kidd's (jkidd's) institution is given as NC State in her profile.  I tried to update it to Old Dominion University, and hit "Save", but it stayed at "North Carolina State University".  I was editing the profile (https://expertiza.ncsu.edu/profile/update/edit).

**Comment by johnbumgardner** [comment]
An interesting bug that seems mainly graphically. The database reflects different institution ids when you change them

**Comment by johnbumgardner** [comment]
<img width="1397" alt="image" src="https://user-images.githubusercontent.com/38589044/161795231-338e507d-efdc-442e-842d-4aaf84b361bb.png">
looked up the assigned institution by id and printed it
