### ISSUE TITLE
My round 2 peer review was overwritten

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#2401]
Rachit Sharma (rsharma26) reports:

I opened one of the link which was in my mail that a submission which I reviewed was updated and after opening that it showed that I updated my review for that with empty scores. You can see in the image it says that update happened on April 25th, 2022. I feel like it's a bug in expertiza which showed up when I opened that link. It also shows up on my timeline that I submitted a new review.

![image](https://user-images.githubusercontent.com/127445/165435283-2c353cb7-0f5e-4c8a-8be9-28f48e7299ba.png)

This was the email I got

Hi,

One of the works you were reviewing for Assignment 'Final project (and design doc)' has been updated since you last reviewed.
Hence, to update your review please click on the following link.
Link: https://expertiza.ncsu.edu/response/new?id=168046
______

Now, the review grader shows both versions of that review, and I can't currently check in Expertiza because reviewing for that assignment was disabled.  But, spontaneous submission of reviews would indeed be a bug.

**Comment by nnhimes** [comment]
In beta the functionality is similar, and I think intended. When you fill out the new rubric, it will display both versions in the UI.
The wording of the email itself has been changed a bit in beta, so a team may have fixed an issue with this if it existed.

![image](https://user-images.githubusercontent.com/41524135/166160183-ee3a3e22-ca92-4761-a680-67a001f5b14b.png)
