### ISSUE TITLE
Non-participants should not be added to teams

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#242]
Right now, teams can be created before participants have been imported.  This is the wrong order.  Importing participants later does not fix the problem; it merely creates a new team for each participant, which overrides the team they were added to earlier.  The system should prevent you from creating teams of non-participants (actually, a better way would be to ask you, when you add a non-participant to a team, whether you want to make them a participant in the assignment).

**Comment by Winbobob** [comment]
This one should be fixed along with #297.
