### ISSUE TITLE
Password retrieval no longer works

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#2427]
Students seem to be unable to use the password-retrieval function successfully.  I have received several requests to change passwords.  This error was just posted by Airbrake:

<html>
<body>

This project is using an outdated version of airbrake-ruby (2.8.1). The latest version is 6.1.*.
--
This is a new error. This project has not received this error before.View error
PROJECTExpertizaENVIRONMENTproductionSEVERITYerrorERROR TYPENoMethodErrorERROR MESSAGEundefined method `[]' for nil:NilClassFILE/PROJECT_ROOT/app/controllers/password_retrieval_controller.rb:11WHEREpassword_retrieval#send_passwordURLhttps://expertiza.ncsu.edu/password_retrieval/send_passwordBACKTRACE/PROJECT_ROOT/app/controllers/password_retrieval_controller.rb:11 in send_password[GEM_ROOT]/gems/actionpack-4.2.11.1/lib/action_controller/metal/implicit_render.rb:4 in send_action[GEM_ROOT]/gems/actionpack-4.2.11.1/lib/abstract_controller/base.rb:198 in process_action[GEM_ROOT]/gems/actionpack-4.2.11.1/lib/action_controller/metal/rendering.rb:10 in process_action[GEM_ROOT]/gems/actionpack-4.2.11.1/lib/abstract_controller/callbacks.rb:20 in block in process_action[GEM_ROOT]/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:117 in call[GEM_ROOT]/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:117 in call[GEM_ROOT]/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:555 in block (2 levels) in compile[GEM_ROOT]/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:505 in call | PROJECT | Expertiza | ENVIRONMENT | production | SEVERITY | error | ERROR TYPE | NoMethodError | ERROR MESSAGE | undefined method `[]' for nil:NilClass | FILE | /PROJECT_ROOT/app/controllers/password_retrieval_controller.rb:11 | WHERE | password_retrieval#send_password | URL | https://expertiza.ncsu.edu/password_retrieval/send_password | BACKTRACE | /PROJECT_ROOT/app/controllers/password_retrieval_controller.rb:11 in send_password[GEM_ROOT]/gems/actionpack-4.2.11.1/lib/action_controller/metal/implicit_render.rb:4 in send_action[GEM_ROOT]/gems/actionpack-4.2.11.1/lib/abstract_controller/base.rb:198 in process_action[GEM_ROOT]/gems/actionpack-4.2.11.1/lib/action_controller/metal/rendering.rb:10 in process_action[GEM_ROOT]/gems/actionpack-4.2.11.1/lib/abstract_controller/callbacks.rb:20 in block in process_action[GEM_ROOT]/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:117 in call[GEM_ROOT]/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:117 in call[GEM_ROOT]/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:555 in block (2 levels) in compile[GEM_ROOT]/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:505 in call
PROJECT | Expertiza
ENVIRONMENT | production
SEVERITY | error
ERROR TYPE | NoMethodError
ERROR MESSAGE | undefined method `[]' for nil:NilClass
FILE | /PROJECT_ROOT/app/controllers/password_retrieval_controller.rb:11
WHERE | password_retrieval#send_password
URL | https://expertiza.ncsu.edu/password_retrieval/send_password
BACKTRACE | /PROJECT_ROOT/app/controllers/password_retrieval_controller.rb:11 in send_password[GEM_ROOT]/gems/actionpack-4.2.11.1/lib/action_controller/metal/implicit_render.rb:4 in send_action[GEM_ROOT]/gems/actionpack-4.2.11.1/lib/abstract_controller/base.rb:198 in process_action[GEM_ROOT]/gems/actionpack-4.2.11.1/lib/action_controller/metal/rendering.rb:10 in process_action[GEM_ROOT]/gems/actionpack-4.2.11.1/lib/abstract_controller/callbacks.rb:20 in block in process_action[GEM_ROOT]/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:117 in call[GEM_ROOT]/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:117 in call[GEM_ROOT]/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:555 in block (2 levels) in compile[GEM_ROOT]/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:505 in call

</body>
</html>This project is using an outdated version of airbrake-ruby (2.8.1). The [latest version](https://github.com/airbrake/airbrake-ruby/blob/master/CHANGELOG.md) is 6.1.*.

This is a new error. This project has not received this error before.	[View error](https://expertiza.airbrake.io/projects/19072/groups/3286786823701398175/notices/3286786798071709503)
PROJECT	[Expertiza](https://expertiza.airbrake.io/projects/19072)
ENVIRONMENT	production
SEVERITY	error
ERROR TYPE	NoMethodError
ERROR MESSAGE	undefined method `[]' for nil:NilClass
FILE	/PROJECT_ROOT/app/controllers/password_retrieval_controller.rb:11
WHERE	password_retrieval#send_password
URL	https://expertiza.ncsu.edu/password_retrieval/send_password
BACKTRACE	
/PROJECT_ROOT/app/controllers/password_retrieval_controller.rb:11 in send_password

[GEM_ROOT]/gems/actionpack-4.2.11.1/lib/action_controller/metal/implicit_render.rb:4 in send_action

[GEM_ROOT]/gems/actionpack-4.2.11.1/lib/abstract_controller/base.rb:198 in process_action

[GEM_ROOT]/gems/actionpack-4.2.11.1/lib/action_controller/metal/rendering.rb:10 in process_action

[GEM_ROOT]/gems/actionpack-4.2.11.1/lib/abstract_controller/callbacks.rb:20 in block in process_action

[GEM_ROOT]/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:117 in call

[GEM_ROOT]/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:117 in call

[GEM_ROOT]/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:555 in block (2 levels) in compile

[GEM_ROOT]/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:505 in call

**Comment by johnbumgardner** [comment]
yeah this is not an issue on prod. seems like the email we use for prod still allows less secure app access, whereas google got rid of this in may 30th 2022. basically airbrake reports bugs that occur anywhere, even in development. we need to find a new test email system to use.
