### ISSUE TITLE
Users must be prevented from dropping a topic after they have submitted on it

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#250]
Currently, there's no check I know of to prevent a user who has submitted on a topic from dropping that topic.  If that happens, it can lead to a number of anomalies, including submissions that cannot be reviewed and users who have submitted to topics that they are waitlisted for (they submitted, dropped the topic, & tried unsuccessfully to reserve it again).

Just like users aren't allowed to drop a topic after a certain date, they shouldn't be able to drop a topic they have submitted to.

**Comment by Winbobob** [comment]
When a team submitted something and tried to drop the topic they chose, there will be an error message says `You have submitted your work, so you are not allowed to drop your topic.`
