### ISSUE TITLE
Uploaded Work for an Assignment is Already There

### ISSUE THREAD

**Issue by akofink** [expertiza/expertiza#253]
We received an email at expertiza-support from Dedra:

>In my assignment "Topic 6 write-up" for the physics 106 course at OSU, when students >are going in to upload their work they are finding that there is work already in the system - >and that appears to be work that was submitted for the previous assignment.  Can >someone look into this please?
>Thank you,
>Dedra

**Comment by efg** [comment]
This is really the same as #391.
