### ISSUE TITLE
Feature Update Notification

### ISSUE THREAD

**Issue by akofink** [expertiza/expertiza#256]
It would be nice to include feature updates for the users of Expertiza when major features are added or changed. This could be simply a one-time notification at the top of the page which links to an article on the details of the change.

Here is a great example of what I am talking about:

![FeatureUpdate](https://f.cloud.github.com/assets/761923/217187/a14ecedc-84e2-11e2-9fb4-9174887b34ed.PNG)

**Comment by yangsong8** [comment]
Part of E1662 in fall 2016, rejected.

**Comment by yangsong8** [comment]
![image](https://user-images.githubusercontent.com/4420550/27141595-9e8f0fd8-50f6-11e7-91aa-6926d00f8a20.png)

I guess we merged this part has been implemented.
