### ISSUE TITLE
Assign reviewers screen gives a walkback

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#2581]
When one clicks on "Assign reviewers" for assignment 1135 (at least), one sees

We're sorry, but something went wrong.

We've been notified about this issue and we'll take a look at it shortly.

**Comment by ameyagv** [comment]
This issue has been resolved.
https://github.com/expertiza/expertiza/commit/2592eacd26fb2f4dc60ba94993b5f9abc6d943b5
