### ISSUE TITLE
More relevant version-control discussion

### ISSUE THREAD

**Issue by sverma5ncsu** [expertiza/expertiza#2608]
The current coverage (last .pptx file from the first day of class) assumes students know little about version control and don't know git.  That's not the case now, since almost all students already have Github accounts.  We should link to background for people to study who don't know git, but the class discussion should focus on the different workflows (distributed, integration manager, etc.) and how to create pull requests and what to put in them.

**Comment by efg** [comment]
With the FOSS workshop slides from March 2023, this problem has been resolved.
