### ISSUE TITLE
Daily Data backup of new server

### ISSUE THREAD

**Issue by shubhangij12** [expertiza/expertiza#2612]
The purpose of this task is to:

- Backup the production database (lin-res103.csc.ncsu.edu) daily
- Transfer the backup file to Development server (152.7.178.10)

Documentation - [DailyDataBackup.md](https://github.com/shubhangij12/expertiza/blob/main/setup/DailyDataBackup.md)

**Comment by efg** [comment]
Shubhangi has created a pull request and is waiting for Ankur to review it.
