### ISSUE TITLE
Some users get the program rubric when reviewing teammates!

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#2680]
For teammate review in CSC/ECE 517 Program 2, Assignment 1144, some students got the Round 1 formative rubric instead of the teammate review!

Look at the team of nbhalla and ychandr.  nbhalla got the Program 2 formative rubric for reviewing his teammate, whereas ychandr got the Standard Teammate Review rubric (which should have been the Review with Github Metrics rubric).

This bug needs to be fixed right away!  We need to use the correct rubric for the OSS project, and its due date is this evening.  So we need to look at the reviews that have already been done, then copy and remove them … as well as fix the bug.

**Comment by qureshi-ali** [comment]
Misconfiguration of assignment led to students getting the wrong rubric for teammate review in the assignment, this was changed to the correct rubric at a later date. Responses with the incorrect rubric were deleted.
