### ISSUE TITLE
Reviews are there, but not the star ratings

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#2743]
From [Piazza](https://piazza.com/class/lqv579dhhf4gp/post/lt15holwbhm77o), 

I submitted 4 reviews for the first review of the Program 2. But when I access the reviews now, I just see the comments and not the star ratings that I gave. It is the same for all the 4 reviews. Only my review comments are visible and not the star rating. I have attached a screenshot of the review here. Kindly let me know what I should do about that!

[Review_4_-_bsudala.png](https://github.com/redirect/s3?bucket=uploads&prefix=paste%2Flli0z8skfpv5m6%2Fb44e3f4e083ed01bcb910b827e66455689929d6dce3c7acff941fe5e796dbbc0%2FScreenshot_2024-02-25_at_01.44.59.png)

**Comment by efg** [comment]
Here is the screenshot:

**Comment by efg** [comment]
Also, if the bottom of the scale is 0, you should not be able to use stars!  (In that case, the score would always be one less than the number of stars selected.)

**Comment by ameyagv** [comment]
This issue may be related to teammate review with the wrong rubric. Two response objects were created, one with the correct question rubric and the other with the wrong one.
