### ISSUE TITLE
"Assign grade" does not work for Assignment 1166

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#2833]
After clicking on "View Submissions" for Assignment 1166 (Final project & design doc, Spring 2024), if I click on "Assign grade" for any team, I get the screen that says,

We're sorry, but something went wrong.
We've been notified about this issue and we'll take a look at it shortly.

"Assign grade" works for the three other assignments I tried, one of which was an assignment with topics.  But it fails for Assgt. 1166 and probably for some other assignments as well.

It needs to work for ALL assignments.

**Comment by ameyagv** [comment]
This issue has been fixed with a db query to remove unassociated rubrics with that assignment. This is occurring due to the rubrics being copied when an assignment is being created by copying another assignment.
