### ISSUE TITLE
Received "454-4.7.0 Too many login attempts" while importing users

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#2840]
I was importing users for this fall's CSC/ECE 517 class.  It (slowly) imported 86 of the 95 records, and then gave the error ...

The following errors were encountered during import.
Other records may have been added. A second submission will not duplicate these records.
454-4.7.0 Too many login attempts, please try again later. For more information,

What does importing users have to do with login attempts?  Is some code being called that should not be?

Oh, and what was that "For more information" link?  It was missing from the error message.

**Comment by ameyagv** [comment]
I was able to import 120 users on the dev server without this error
