### ISSUE TITLE
Merge the two wikis to one, and host it on github

### ISSUE THREAD

**Issue by ghost** [expertiza/expertiza#294]
The two wikis are these:

-- http://wikis.lib.ncsu.edu/index.php/Expertiza
-- http://wiki.expertiza.ncsu.edu/index.php/Main_Page

We need to merge them and host all the relevant documentation on github to have a central place to look for documentation. Please add anything else that you want to add to the documentation in your comments here.

**Comment by efg** [comment]
Long outdated ...
