### ISSUE TITLE
Add a confirmation on deleting an assignment on the admin screen

### ISSUE THREAD

**Issue by ghost** [expertiza/expertiza#295]
Currently when admin/instructor tries to delete an assignment, there is no alert/confirmation shown. This is risky. We need to add a confirmation step to avoid losing data.

**Comment by efg** [comment]
If any reviews have been written, the instructor is asked to confirm.  Even if not, the system should still ask the instructor.  Not clear if this happens.

**Comment by yangsong8** [comment]
Part of E1662 in fall 2016, rejected.

**Comment by ferryxo** [comment]
Using the production system, I tried to create an assignment and delete it directly. It prompted for a confirmation.
