### ISSUE TITLE
Send out an email to the invitee when a participant sends out an invite to another participant for joining team

### ISSUE THREAD

**Issue by ghost** [expertiza/expertiza#296]
Send out an email to the invitee when a participant sends out an invite to another participant for joining team. Check if this is included in the email notification project that Korak worked on. Otherwise treat this as a new feature

**Comment by efg** [comment]
Still extant after all these years!

**Comment by efg** [comment]
Student who issued the invitation should also be e-mailed when the invitee joins the team.  And also when a student responds to a teammate advertisement.  In general, all activity on ad responses and invitations should be reported to the other party by e-mail (unless these e-mails are turned off in a (new) profile field).

**Comment by yangsong8** [comment]
Part of E1655 in fall 2016, rejected.

**Comment by efg** [comment]
This is part of E1785, which needs to be redone.
