### ISSUE TITLE
Inviting team member should complain if user is not a participant

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#297]
In the current master branch, when someone invites another user to join their team for an assignment, if the other user is not a participant in the assignment, nothing happens; the inviter is just returned to the same screen, which shows no pending invitations.

Instead, the inviter should be notified that the invitation cannot be sent, because the invitee is not a participant in the assignment.

**Comment by Winbobob** [comment]
Yes, there will be a message says `[UnityID] is not a participant of this assignment.`
