### ISSUE TITLE
$ variable in java-script 

### ISSUE THREAD

**Issue by hliu115288339** [expertiza/expertiza#305]
the widely accepted convention is to assign $=jQuery
i found out that $ has been assign to an weird function globally 

I suggest that we get sort out this problem

current function that $ is assign to 
function $(element) {
  if (arguments.length > 1) {
    for (var i = 0, elements = [], length = arguments.length; i < length; i++)
      elements.push($(arguments[i]));
    return elements;
  }
  if (Object.isString(element))
    element = document.getElementById(element);
  return Element.extend(element);
}

**Comment by Winbobob** [comment]
We can check the usage of `prototype.js`.

**Comment by efg** [comment]
We can't find the protoype.js file now, so it seems that this has been fixed or superseded.
