### ISSUE TITLE
Needed: a way to set all deadlines ahead (or behind) a certain number of days

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#309]
When doing testing, we very often want to test an assignment in, say, the submission or review phase, even after the assignment is complete.  In order to do this, we need to change several due dates from the UI.  It would be a lot easier if we just had a command that said, "set all due dates ahead by x days.

This would also be useful for copying last semester's assignments into this semester's courses.

**Comment by yangsong8** [comment]
Part of E1654 in fall 2016, merged.
