### ISSUE TITLE
Remove unused deadline types from deadline_types table

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#310]
Hao has removed the resubmission and rereview columns from the deadline tableau in the assignment_controller.  Resubmission and rereview permissions are no longer used in the system.  Thus, they (ids 3 & 4) should be removed from the deadline_types table.  Ideally, other type ids should be adjusted.  Be careful of any deadline-type constants that may be included in the source code.

**Comment by Winbobob** [comment]
Fixed by Yang.
