### ISSUE TITLE
Prospective team member should only be able to respond to an ad once

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#311]
When a team advertises for new members, someone who responds to an ad should only be allowed to respond once.  Currently, after someone responds to an ad, they can respond again an unlimited number of times.

**Comment by efg** [comment]
Then in E1779, partially merged.  Not clear if issue is fixed, though.

**Comment by ryanhardy002** [comment]
This is still an issue in beta as of 1/27/2022. Possible fix is to add an edit feature in join_team_request_controller and change the view to have an edit button rather than a request button if one request as already been submitted.

**Comment by johnbumgardner** [comment]
> This is still an issue in beta as of 1/27/2022. Possible fix is to add an edit feature in join_team_request_controller and change the view to have an edit button rather than a request button if one request as already been submitted.

this is how id approach it. can you implement this fix?

**Comment by ryanhardy002** [comment]
It is also possible to request to join your own team. This should not be the case.
