### ISSUE TITLE
Topic_id should be stored in Teams table, not in Participants table

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#313]
Now that individual assignments have been removed from Expertiza (I think :-), we should move the topic_id from the participants table, where it is currently stored, to the teams table.

As long as topic_id is in the participants table, it is possible for different team members to be assigned different topics.  This won't happen if the code is bug free, but if a bug causes this to happen, we would have no way to determine which topic the team is really signed up for.

**Comment by Winbobob** [comment]
Fixed by Yang.
