### ISSUE TITLE
"Actions" column should not appear on signup sheet in a completed assignment

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#316]
If an assignment is completed, no one can sign up for topics or drop topics.  Yet a completely blank "Actions" column on the signup sheet still appears.  It would be better if the column did not appear.

**Comment by Winbobob** [comment]
If one assignment is over, students cannot drop topics anymore.

**Comment by yangsong8** [comment]
Part of E1662 in fall 2016, rejected.

**Comment by yangsong8** [comment]
But this feature has gone in Expertiza.
![image](https://user-images.githubusercontent.com/4420550/27045839-40de0e52-4f70-11e7-9574-99a027bb1226.png)
