### ISSUE TITLE
A 'final submission' check box needed on 'your work' page

### ISSUE THREAD

**Issue by yangsong8** [expertiza/expertiza#321]
This is a suggestion by Teddy.

When a student submits his/her work, maybe he/she does not want this to be reviewed by others immediately because it has not been finished yet. The ideal solution might be add a 'final submission' check box. If the student submits something not ready for review, he/she would not check this box, and this submission will not be reviewable yet. Students' work will only be reviewable when they check that box, or after the end of the submission phase.

**Comment by efg** [comment]
On third thought, let's just have "reviewable" checked by default.  Then anyone who wants their work not to be reviewable can uncheck it.
