### ISSUE TITLE
'parent_id' in 'Team' duplicates 'parent_id' in 'TeamNode' 

### ISSUE THREAD

**Issue by teddywupei** [expertiza/expertiza#326]
'parent_id' in 'Teams' table stores the same information as 'parent_id' in 'Nodes' table.  This leads to an unnormalized db, and needs to be refactored.

**Comment by Winbobob** [comment]
Yes, for `TeamNode` type, `parent_id` in `teams` table stores the same information as that field in `nodes` table. However, for other node types, `parent_id` stores different kind of information.
