### ISSUE TITLE
Import fails to insert new members into an AssignmentTeam 

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#328]
This bug occurred when we tried to import a team and selected 'Insert any new members into existing team'. No new team members were in fact inserted into the team.

**Comment by yangsong8** [comment]
E1656 rejected.

**Comment by johnbumgardner** [comment]
This bug still exists.

**Comment by johnbumgardner** [comment]
Found where the bug existed. You must be able to import <2 teammembers.

**Comment by johnbumgardner** [comment]
Fixed
