### ISSUE TITLE
For elegance, coalesce AssignmentTeam and CourseTeam creation

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#332]
When an AssignmentTeam or CourseTeam is created, a companion TeamNode is created for it so that the teams can be displayed in a list under their course or assignment name.  We've written separate create_team_and_node methods for AssignmentTeam and CourseTeam.  But we'd like to collapse them into a single method, as is done when team_controller.rb>>create creates a team (it computes whether it should be an AssignmentTeam or a CourseTeam, then concatenates the "Assignment" or "Course" with "Team" before calling the create method.

Figure out an elegant way of doing this, then replace the 6 calls of AssignmentTeam. or CourseTeam.create_team_and_node by calls to the the new create_team_and_node.  Also take the calls in team_controller.rb and team.rb that compute the class of the object they are creating, and make them call the new method too.

**Comment by yangsong8** [comment]
Part of E1651.
