### ISSUE TITLE
All questions in a rubric section evidently need to be consecutive

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#337]
One should be able to edit a rubric and add a question to any section of the rubric.  Unfortunately, if one adds a question to the end of an existing rubric, specifying a section that is not the last section of the rubric, the new question creates a *new* section of the rubric whose name is the same as the existing section.  For example, I tried to add a question to the Ratings section of the CSC/ECE 506 Wiki Custom Review rubric.  The Ratings section is the first section of the rubric.  The question that was added created a *new* Ratings section, so now there were two Ratings sections, one at the beginning of the rubric and one at the end.

One could work around this by creating a question at the end of the rubric and then *moving* it to its proper section--except that there is currently no way to rearrange questions in a rubric!

**Comment by yangsong8** [comment]
With the refactoring done in summer 2015, we are able to do this with the sequence number of each question.
