### ISSUE TITLE
Teams with null type fields created--somehow--for an assignment

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#339]
This is a problem that occurred with an assignment created on account ucf_coe on September 5 or 7, 2013.  Teams were created for all the participants in this individual assignment (max_team_size = 1), even before they signed up or tried to submit anything.

Normally, in an individual assignment, teams are only created when the user signs up for a topic, or submits work, whichever comes first.  In this case, teams were created for all the participants before either of these two events occurred.  Moreover, instead of being AssignmentTeams or CourseTeams, the type field for these teams was null!  This caused problems when the code tried to get the team members, as get_team_members is not defined for nil objects.

In discussions with Maura Austin, the TA for the course, we were not able to determine how this happened.  She had trouble importing users for her first assignment (end-of-line problems caused by writing on one OS and reading on another) and then created a new assignment, which was working OK.  It was just the first assignment she created that had problems with team creation.

Yang & I looked all through the code and couldn't find anyplace where a team was created that was not a CourseTeam or an AssignmentTeam.  There is a method self.upload_teams in TeamHelper that creates plain Teams, but this method is not called anywhere in the code base.

So this is still a mystery.  It's probably not easy to trigger this bug, but we would like to get rid of it!

**Comment by yangsong8** [comment]
From db query, the largest id of team with null type is 15***. We do not have this issue for a long time.
