### ISSUE TITLE
Expertiza says to revise review after assignment has ended

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#346]
Expertiza is telling a student to revise his review more than a week after the assignment ended:

---------- Forwarded message ----------
From: expertiza-support@lists.ncsu.edu
Date: Fri, Oct 18, 2013 at 5:05 PM
Subject: A new submission is available for Backchannel app
To: knjhaver@ncsu.edu

Hi Krunal,

One of the submissions you are reviewing for the "Backchannel app" assignment has just been entered or revised. You may log into Expertiza and review the work now.

This message has been generated by Expertiza
http://expertiza.ncsu.edu

---

Reminders, of course, should only be sent when a review period is in progress or forthcoming.

**Comment by Winbobob** [comment]
This issue is related to email notification, which is not easy to reproduce. In this case, I close this issue. If similar cases happen later, we can look into it.
