### ISSUE TITLE
Need to refine strategy for determining which work is reviewable

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#349]
If reviewing is "auto-selected" (or, I think, "student-selected"), only the work that has the least reviews so far can be reviewed.  If this is the prospective reviewer's own work, since (s)he cannot review his own work, (s)he will be unable to review.  The strategy needs to be changed to allow a reviewer to review the least-reviewed work _by someone else_.

**Comment by Winbobob** [comment]
See issue #402.
