### ISSUE TITLE
Users table should use single-table inheritance

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#351]
The `users` table contains all kinds of users (admins, instructors, TAs, etc.).  It _could_ use single-table inheritance to encode the various kinds of users.  Then methods could be written in the various classes that would do the right thing, e.g., TA>>courses_assisted_with.  This would require a data migration to fix the `users` table.

However, this isn't a slam-dunk solution, because the permissions of the various user types are not necessarily hierarchical.  That is, while currently a TA's permissions are a superset of students' permissions, and an instructor's permissions are a superset of a TA's permissions.  But if the rights change at some point so there are two types of users who have overlapping sets of permissions, single-table inheritance can't encode that properly.

Additionally, if a user is a TA in one class, but taking another class, they should act as a student in the second class.  Methods of Student class should work if applied to them.  What we'd really like to do is to have a user who is _both_ a TA and a student.

**Comment by Winbobob** [comment]
Already fixed by adding `role_id` into `users` table.
