### ISSUE TITLE
Can't create user from UI without a comma or dot in the full name

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#366]
When creating a user from "Mange > Users", if the full name does not contain a comma or a dot, then a walkback occurs.

The culprit is line 45 of users.rb: `fullname[/,.+/][/\w+/] if fullname`

The regexp subscript needs to be changed.  I'm not sure how doubly subscripted regex arrays work at this point.

**Comment by yangsong8** [comment]
Cannot test for now, need to get user_controller/list fixed first. =(

**Comment by yangsong8** [comment]
We don't have this issue on Expertiza anymore.
