### ISSUE TITLE
Not getting the option for signup on the signup sheet

### ISSUE THREAD

**Issue by bhumikadhotre** [expertiza/expertiza#377]
Line number 251 in the signup sheet controller sets a flag to make the actions on the signup sheet visible/ invisible.
Even after the signup deadline is not due, the action buttons are made invisible.

Also, even after I remove this condition and make the buttons visible, I am not able to signup, as it gives this exception 

![exception](https://f.cloud.github.com/assets/5685308/1603626/62d9452a-53ad-11e3-93b3-4a69385680d8.png)

**Comment by yangsong8** [comment]
This should be related to using sign_up_deadline. We should double check this. We rarely use sign_up_deadlines.

**Comment by yangsong8** [comment]
I test this and after the sign up ddl, the action buttons will not be available in current Expertiza master.
