### ISSUE TITLE
Prevent assignments from sharing a directory

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#391]
We have had many bad situations when two assignments share a submission directory.  Usually this has been from the bug in copying assignments (which I hope is still fixed).  Today it happened because an instructor (karl.schmitt) created two different assignments without specifying a submission directory, so that both of the assignments were in his home directory.

To prevent this, the system should warn when ..
- creating an assignment but not specifying a submission directory (though this may be perfectly reasonable if the instructor only expects links to be submitted), and
- creating an assignment that uses a submission directory that is already in use by another assignment.

**Comment by yangsong8** [comment]
Might be fixed, I will double check

**Comment by efg** [comment]
Also see the (long) discussion in #253

**Comment by yangsong8** [comment]
I have checked this, this issue is till in Expertiza.

**Comment by yangsong8** [comment]
This is still in Expertiza.

**Comment by efg** [comment]
This is still extant as of June 2018, though it is addressed by E1782, Assignment directories, which is planned to be merged.
