### ISSUE TITLE
Reviewer can attempt to delete hyperlinks submitted by the project under review

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#392]
When doing a review, a reviewer is shown the hyperlinks & submitted files for the project that is being reviewed.  The UI allows the reviewer to delete these hyperlinks!  Or at least it appears to; clicking on "delete hyperlink" will bring up an error screen that says, "No method responded to delete_link."

The authors, obviously, should be able to delete their hyperlinks; reviewers should not.

**Comment by yangsong8** [comment]
Should be fixed..
