### ISSUE TITLE
Review threshold needs to be more intelligent

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#402]
The review threshold prevents a reviewer from reviewing submissions that currently have "too many" reviews.  If the threshold is 0, the reviewer is allowed to choose only the submission(s) with the fewest number of reviews so far.  If the threshold is _k_, the reviewer is allowed to review any submission that has within _k_ reviews of the submission with the fewest reviews so far.

However, suppose the reviewer's submission is the submission with the fewest reviews so far.  Then the reviewer will be allowed to select his/her own submission to review, but upon selecting it will be told, "There are no more submissions to review on that topic."  Not only is this a cavalier exception message, but the reviewer won't be able to review anything at all--not till someone else reviews the reviewer's own submission.

This should be fixable very easily.  The candidate_topics_to_review method of assignment.rb needs to be modified to exclude the reviewer's submission.  Probably, the reviewer's identity will have to be passed to candidate_topics_to_review.

**Comment by yangsong8** [comment]
This is part of E1718

**Comment by efg** [comment]
Part of E1777, OSS Project Green , which is planned to be merged.

**Comment by Saurabh110** [comment]
The project is merged in the Master branch ( #1315 & #1059)
