### ISSUE TITLE
Can't assign an assignment to a course

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#403]
When I attempt to assign an assignment to a course, I get this walkback:

NoMethodError in Assignment#associate_assignment_with_course

Showing app/views/assignment/associate_assignment_with_course.html.erb where line #1 raised:

undefined method `name' for nil:NilClass
Extracted source (around line #1):

1: <h1>Courses available for <%= @assignment.name %></h1>
2: 
3: Select a course to which the assignment will belong:
4: <BR/><BR/>
RAILS_ROOT: /local/rails/expertiza/releases/20131118193146

**Comment by yangsong8** [comment]
This bug does not exist in the current version now.

We can click the 1st icon in the 2nd line to assign an assignment to a course: 
![image](https://cloud.githubusercontent.com/assets/4420550/14968738/88b88384-108c-11e6-984a-8b1c7ddc7f30.png)

Or we can click the "pencil icon" then select the course from the dropdown: 
![image](https://cloud.githubusercontent.com/assets/4420550/14968766/a30c65fc-108c-11e6-9f08-ec26f8f43c38.png)

Both approaches work fine now.
