### ISSUE TITLE
Assigning to a course needs to move submission directory!

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#404]
When an assignment is assigned to a course, and it already has submissions, those submissions need to be moved to a place under the directory for the course.

Here's why.  When an assignment is created outside of a course, the instructor specifies a path for the directory where the submissions are supposed to be kept.  This path begins with the instructor's directory.  But, when an assignment is created inside a course, the path begins with the course directory … which is a subdirectory of the instructor's directory.  So when an assignment is assigned to a course, its submission directory normally needs to be moved.

HOWEVER … even when creating an assignment outside of a course, the instructor may have specified a submission directory that has the course name in the pathname, e.g., csc517/s14/assignment1.  So, before moving the submission directory, the code needs to check that the course directory is not already an initial substring of the submission directory.  If it is, the submission directory should not be moved.

**Comment by Winbobob** [comment]
If the instructor try to move an assignment from one course to another course, the directory needs to be moved too.

**Comment by efg** [comment]
This was part of E1782, OSS Project Red, which is planned to be merged.

**Comment by Saurabh110** [comment]
The project E1782 is merged in the Master branch #1070
