### ISSUE TITLE
Reviewer report for individual assignment reports wrong team names

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#405]
For "individual" assignments--those with a max_team_size of 1--the Reviewer report lists the wrong teams being reviewed.  My suspicion is that it is using the user ID in place of the team_id.

Here is an example:

![image](https://f.cloud.github.com/assets/127445/2300523/5c0df5b0-a0f6-11e3-95fd-bf621e8fd234.png)

Cecile Burnett et al. are not students in the class.

Actually, the reviewer report should not list the team names (of the 1-member teams), but rather the name of the user who is on the team.

**Comment by yangsong8** [comment]
![image](https://cloud.githubusercontent.com/assets/4420550/15186169/051038b2-176a-11e6-8834-cb32b1f89b06.png)

The issue is a little bit different now. For current version, the reviewers are displayed in names but the reviewee are still displayed in the team names.
