### ISSUE TITLE
Can't review in staggered-deadline assignments

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#406]
In Wiki A for Spring 2014, tthampy was not able to begin a review.  There was no "Begin" link on the reviews she selected.  As soon as I changed the assignment to not be a staggered-deadline assignment, review became possible.

This is a similar case to the one we had yesterday when sramesh3 got a no-method error for a nil due_date on the New Problems A assignment when it was a staggered-deadline assignment.

**Comment by Winbobob** [comment]
We should probably remove the `topological sort`.

**Comment by efg** [comment]
Fixed in Fall 2016.

**Comment by yangsong8** [comment]
Should have been fixed by Zhewei
