### ISSUE TITLE
Accepting a teammate needs to be an indivisible action

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#407]
If someone invites someone else to join a team, and when that other person accepts the invitation, if this would put the team over the size limit, the respondent is NOT added to the team (this is correct), but the invitation is still marked as accepted (this is incorrect).  When someone is accepted on a team, the actions that ensue need to be done indivisibly.

**Comment by yangsong8** [comment]
I have checked it again. Now the logic is correct in master branch.
