### ISSUE TITLE
Review requirement needs to be obvious to students

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#417]
Students often tell me that they don't know how many reviews they are required to do.  It would be nice if the Others' Work page said at the top, "You are required to do k reviews and m metareviews."  (Ideally, the message about metareviews would be in the metareview section.)

**Comment by yangsong8** [comment]
Should be added to "review-strategy" tab, with default 3.

**Comment by Winbobob** [comment]
`Maximum number of reviews` show allow `per submission` and `per reviewer` regardless of which review strategy is used.

**Comment by yangsong8** [comment]
We can add another field to assignment table. The field can be called "num_review_expected".
