### ISSUE TITLE
Metareview deadline being displayed in-spite of not selecting it.

### ISSUE THREAD

**Issue by krunaljhaveri** [expertiza/expertiza#427]
While clicking on metareview link, it throws up an error in studentReview controller.

**Comment by yangsong8** [comment]
![image](https://cloud.githubusercontent.com/assets/4420550/14968194/9e0cb99c-1089-11e6-9646-3b97053de07a.png)

![image](https://cloud.githubusercontent.com/assets/4420550/14968204/a804649a-1089-11e6-9750-8000acfd74f6.png)

This works with current javascript now.
