### ISSUE TITLE
Mysql2::Error: Unknown column 'nodes.rgt' in 'order clause': SELECT `nodes`.* FROM `nodes` ORDER BY `nodes`.`rgt` desc LIMIT 1

### ISSUE THREAD

**Issue by lianalinchen** [expertiza/expertiza#463]
![screen shot 2014-12-03 at 9 22 03 pm](https://cloud.githubusercontent.com/assets/5454576/5292651/fcf1d84a-7b32-11e4-8bf9-3c1e79a6828b.png)

When student pick a topic from signup sheet, this page will show up, indicating Unknown column 'nodes.rgt' in 'order clause'

**Comment by yangsong8** [comment]
I don't see this bug in current my testing.
