### ISSUE TITLE
Cannot start a review

### ISSUE THREAD

**Issue by yangsong8** [expertiza/expertiza#480]
After student select a topic and try to click "begin" and start a peer-review, a error message shows, indicating that an assignment team object was passed when the code expects a participant object.

**Comment by efg** [comment]
Of course, the code *should* be expecting an assignment team, since only
teams can participate in assignments in the current Expertiza.

**Comment by yangsong8** [comment]
Yes sir. One more question on this issue: 

Say, user 1 and user 2 are in the same group for an assignment and they submit "www.user1.com" and "www.user2.com" respectively. And user 3 is the peer-reviewer for their artifact.

In this case, user 1 and user 2 can both delete the hyperlinks submitted for this assignment, no matter the hyperlinks are submitted by whom, but user 3 can delete none of the links. Is this the way we want this feature to be implemented?

**Comment by efg** [comment]
Yes, that sounds right.  Peer reviewers should not be able to delete the
work they are reviewing.
