### ISSUE TITLE
Response to custom rubric cannot be saved.

### ISSUE THREAD

**Issue by yangsong8** [expertiza/expertiza#486]
I used an ordinary review rubric in round 1 and all the responses can be saved properly. In round 2 a custom rubric is used and when I click save, I got the error message below:

![image](https://cloud.githubusercontent.com/assets/4420550/6201717/f22a72f8-b487-11e4-87cb-88abb6dfd354.png)

**Comment by nchinth** [comment]
Fixed this issue and checked in the code.
