### ISSUE TITLE
Reviews cannot be edited (in the same round)

### ISSUE THREAD

**Issue by yangsong8** [expertiza/expertiza#494]
In rails 4 branch if user tries to edit a existing review done in the same round, an error message will be displayed:
![image](https://cloud.githubusercontent.com/assets/4420550/6363791/adfcccac-bc6b-11e4-8830-f7ffb84fffab.png)

**Comment by yangsong8** [comment]
It seems to me that it is cause by some configuration mistake in /config/routes.rb

**Comment by nchinth** [comment]
Is Someone looking into this? or else i can take this up

**Comment by yangsong8** [comment]
Please look into this issue, thanks. --Yang

**Comment by yangsong8** [comment]
Hi Nikhil Ch, please submit you commit and close this issue.

**Comment by nchinth** [comment]
Fixed and commited the code change to rails4 branch
