### ISSUE TITLE
Joining a team causes expertiza to lose everything you've done on your previous topic

### ISSUE THREAD

**Issue by nilbus** [expertiza/expertiza#5]
While one cannot sign up for two topics in the same assignment, after doing one topic, one can join someone else's team.  And if you do that, Expertiza "forgets" that you've done your previous topic.  Your reviews on the first topic then need to be retrieved from your partner's display or from database queries!  (Discuss w/Ed ideas on how to fix this.)

**Comment by yangsong8** [comment]
In current Expertiza, one can still leave a team after this team has made a submission and got reviewed.
The record in teams table got deleted, too.

I am not sure if this is the correct thing to do, but we should not force the last person to stay in the team even the artifact has been reviewed, right?

**Comment by yangsong8** [comment]
Updated: when the last team member leave but the work have been reviewed, the team record in db stays.
