### ISSUE TITLE
[assignment with team without topic]Students cannot request artifact for peer-review

### ISSUE THREAD

**Issue by Winbobob** [expertiza/expertiza#501]
I create an assignment with team without topics. In review stage, I cannot request artificat for peer-review in Round 1. It seems that assignment with topics can let students choose artifact for peer-review.

**Comment by yangsong8** [comment]
Hi Zhewei, in this scenario you will not see the topic list. But you can check the "I don't care which artifact to review" box and then click "request" button. Ideally you should have a random artifact (or an error message will be flashed). Please pull the newest version of Expertiza first.

**Comment by Winbobob** [comment]
Thanks @yangsong8, after pull the newest version, I can request artifact for peer-review now.
