### ISSUE TITLE
Author feedbacks cannot be edited (in the same round)

### ISSUE THREAD

**Issue by Winbobob** [expertiza/expertiza#503]
When author want to add feedback, it will also show the error<b> "No route matches [POST]"</b>, the same as #494, but the data still be added in database. And if author want to edit an existed feedback, another error will occur. See the image below.
![1](https://cloud.githubusercontent.com/assets/7702035/6427570/ba9fffe4-bf52-11e4-9b46-2562fb0fc68e.png)

**Comment by Winbobob** [comment]
I think maybe it is bacause this function cannot obtain the id parameter in URL. And it seems that "56224" is the id number we need.

**Comment by yangsong8** [comment]
This feature works on current production.
