### ISSUE TITLE
If first time new-user creation occur some unsatisfaction, cannot create new users any more

### ISSUE THREAD

**Issue by Winbobob** [expertiza/expertiza#504]
![expertiza_bug](https://cloud.githubusercontent.com/assets/7702035/6432340/6c5a4ec4-c01b-11e4-9a16-b041413bb076.png)

**Comment by Winbobob** [comment]
The only way to create new users again is clear your browser's cache.

**Comment by Winbobob** [comment]
In Rails 4.1. these are no longer deprecation warnings if ```with_scope```, but errors.

**Comment by Winbobob** [comment]
This bug has been fixed by @yatish27. And the way to fix this bug is to update the ```Gemfile``` to newest version.

**Comment by yatish27** [comment]
Not just updating the gem. the authlogic expertiza needed some changes. I fixed that in the expertiza/authlogic repo.
