### ISSUE TITLE
"Has topics" checkbox should be removed

### ISSUE THREAD

**Issue by yangsong8** [expertiza/expertiza#521]
*The “Has topics” button on the General tab will be removed.
*The “Intelligent topic selection” button will be moved to the Topics tab.
*If an instructor adds a topic to an assignment having no other topics either from the UI or by importing topics, a notifier will pop up and warn the instructor that, “You have added [a topic][topics] to this assignment.  Students will now have to select a topic before they submit their work.”

**Comment by Winbobob** [comment]
Fix 3rd sub-issue: pop up warning dialog.
