### ISSUE TITLE
Instructor should not be permitted to add an arbitrary user to a course

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#536]
There is an issue with an instructor adding an arbitrary user as a course participant or an assignment participant.  If not fixed, then any instructor anywhere in the system can get access to any student’s work simply by adding them to a course or assignment and impersonating them.  Solution proposed by Nikhil J. is to require each user (not created by the instructor?)  to confirm that they want to be added to the course or assignment.

**Comment by yangsong8** [comment]
We got a better idea in our discussion on July 27, 2016:

The instructor can only see students' work within his/her own course/assignment when the instructor impersonates students. This will work for instructors, but admins or super-admin should still see all the work done by each student.

**Comment by efg** [comment]
For security reasons, if an instructor tries to get access to an existing account that they did not create, then the student (or other user) should be e-mailed and told that the instructor wants access, and asked whether to grant that access.

**Comment by johnbumgardner** [comment]
@nnhimes can you implement this as described via the email prompt?

**Comment by nnhimes** [comment]
Instructors can no longer impersonate students that they did not create. You can add students that exist to a course/assignment, but impersonation gives this error
![image](https://user-images.githubusercontent.com/41524135/155236066-2b0d4a35-41dc-423b-95ea-08eff55e89fd.png)
