### ISSUE TITLE
Review strategy: student-select should be removed, instructor-select should be maintained.

### ISSUE THREAD

**Issue by yangsong8** [expertiza/expertiza#538]
Student-selected review strategy does not work (i.e., when a student attempts to do a review, a walkback occurs) (and it’s the default when an assgt. is created--the default should be “auto-selected”).  

- [x] We will just remove student-selected reviewing. 
- [x] The instructor-selected feature should still be maintained.
- [x] Change the pop-up info on the "review strategy" tab

**Comment by yangsong8** [comment]
After clicking "other's work", nothing shows in students' interface if the review strategy is "instructor-selected".
![image](https://cloud.githubusercontent.com/assets/4420550/7151115/3063df98-e2f3-11e4-9f16-880324b3b970.png)

**Comment by yangsong8** [comment]
Instructor can assign reviewers from UI:
![image](https://cloud.githubusercontent.com/assets/4420550/7151198/74151ee0-e2f4-11e4-821d-021d9f7ece2f.png)

**Comment by yangsong8** [comment]
After that, the student can do the reviews assigned by instructor. This is an assignment without topic.
![image](https://cloud.githubusercontent.com/assets/4420550/7151207/90746280-e2f4-11e4-99e3-e35cb28e1491.png)

**Comment by efg** [comment]
Good job.  Thanks!

-Ed
