### ISSUE TITLE
Students should have access to "Other's work" after the due dates

### ISSUE THREAD

**Issue by yangsong8** [expertiza/expertiza#539]
After the review period is over, a user should still be able to see reviews that (s)he has authored.  Currently, “Others’ work” is grayed.

**Comment by yangsong8** [comment]
In current Expertiza (both Rails 4 and production), after the last due data students are not allowed to click "others' work".
![image](https://cloud.githubusercontent.com/assets/4420550/7160308/27c52cf8-e356-11e4-8fe7-420945a47c13.png)

I have enabled this link, but the new question is, after the last due date, should students still be able to update reviews or request new artifact to review?

**Comment by yangsong8** [comment]
The newest version is, allow students to "view" the peer-review feedback but not allow students to select new reviews or update existing reviews.

This is students' "others' work" view for a "finished" assignment with topics:
![image](https://cloud.githubusercontent.com/assets/4420550/7161495/659cdefc-e35d-11e4-9b29-630833f761bc.png)

This is students' "others' work" view for a "finished" assignment without topic:
![image](https://cloud.githubusercontent.com/assets/4420550/7161548/9f1c2d22-e35d-11e4-9f41-fab624773ef3.png)

**Comment by efg** [comment]
Looks great.  Thanks!
