### ISSUE TITLE
Adding slot when someone is waiting does not work correctly

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#540]
This is from the production branch, but probably applies to rails4 as well, because I don't think the code has been changed.

I just added a slot for a student who was waiting for several topics when no topic was available.

When I added the slot, I got a Rails error (I did not think to copy down what kind of error).  It did not change the number of slots for the topic (which was 1), but it did show that –1 slots were now available.

Then I tried again.  Now it succeeded; the number of slots was changed to 2, and the waiting student got the slot.

But, he was still on the waiting list for the other topics.  And, when a waiting students gets a topic (s)he is waiting for, (s)he should be purged from all the waitlists.  This is not happening.

**Comment by yangsong8** [comment]
This is case 4 in OSS E1554 in Fall 2015.

**Comment by yangsong8** [comment]
Might work, we should test it.

**Comment by yangsong8** [comment]
![image](https://cloud.githubusercontent.com/assets/4420550/15132424/933912c4-1627-11e6-9c92-48408766b50d.png)

![image](https://cloud.githubusercontent.com/assets/4420550/15132448/bb384196-1627-11e6-87d1-7aace5e29b15.png)
I have double checked this and this feature works.
