### ISSUE TITLE
Student_task/list view is broken 

### ISSUE THREAD

**Issue by yangsong8** [expertiza/expertiza#555]
When impersonating student account I got error message below. Seems to me that this is cause by merging.
![image](https://cloud.githubusercontent.com/assets/4420550/7717756/8d149e48-fe74-11e4-855d-eb47373ec3e0.png)

**Comment by p31-d3ng** [comment]
oh sorry I didn't check it throughly. I am trying to fix it now.

**Comment by yangsong8** [comment]
After fixing the code above, there is still another error message cause by the code relate to teammates list. The reason was that E1525 did not consider the case that there might be assignments which are not associated with any course.
