### ISSUE TITLE
submitted_hyperlinks needs to be moved to teams table

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#565]
Currently, submitted hyperlinks are saved in the participants table, in the record for the participant who submitted the hyperlink.  This is inappropriate now that individual assignments have been removed.  Submitted hyperlinks should be stored in the teams table.

**Comment by yangsong8** [comment]
This is E1564 project is OSS project in 2015 fall now.

**Comment by yangsong8** [comment]
This is done in E1564 and further done in E1601. Both of them have been merged.
