### ISSUE TITLE
If instructor assigns someone to review own team, it needs to count as self-review

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#570]
Currently, instructors are not allowed to assign users to review their own team.  It might make sense to allow this, but if it is allowed, it needs to be scored as a self-review.  This means it needs to be harmonized with the code in expertiza/app/views/submitted_content/_selfreview.html.erb.

**Comment by yangsong8** [comment]
Part of E1600 written by  Yang.

**Comment by yangsong8** [comment]
E1600 has been merged.
