### ISSUE TITLE
Quiz authors should not be able to change the quizzes after they are taken

### ISSUE THREAD

**Issue by yangsong8** [expertiza/expertiza#572]
In the quizzing feature, the quiz authors now are able to change the quiz questions at any time. This is not a good design. They should not be able to change the quiz question is the quiz has already been taken. There should also be a info icon remind the authors about this.

**Comment by efg** [comment]
I don't know about this.  If a question is mis-worded, then the quiz author
should be able to fix it before anyone else takes the quiz.  If there is a
typo, it should be possible to correct it.  Prohibiting all changes seems
like bad design.  Arguably, one should not be able to change the questions
after *all* students have taken the quiz.  But even here, there is room for
argument.  Perhaps the instructor wants to fix the quiz so it will be
correct the next time it is assigned to a class.

**Comment by yangsong8** [comment]
After discussing with Dr. Gehringer, we decide that the quiz editing should be available any time before the assignment is finished. Since the quiz authors may change anything in the quiz (could be typo fix, or change the whole question), the quiz taking records should be flagged as "invalid" if the quiz author does any change to the quiz questions after the quiz has been taken by some one. So the quiz taking records should not be counted. We need to check the update time of quiz questionnaire and the quiz taken time (probably in response map).
