### ISSUE TITLE
Better messages from action_allowed

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#573]
Currently, if an action is not allowed, the action_allowed method flashes, "Permission Denied to [controller#method] to this [role]".  This is programmer-speak.  It would be better if it said something like, "This [role] is not allowed to [method] this [controller]."

**Comment by yangsong8** [comment]
This is fixed. I log in as student and paste the hyperlink "http://0.0.0.0:3000/assignments/729/edit". When I hit enter I see this error message:
![image](https://cloud.githubusercontent.com/assets/4420550/9701915/ba330c18-5412-11e5-8dc4-17e6acff480b.png)
