### ISSUE TITLE
[project idea] Fix dumping and loading rubric criterion from csv

### ISSUE THREAD

**Issue by yangsong8** [expertiza/expertiza#577]
This seems to be an OSS project to me.

Expertiza team did a significant refactoring on questionnaire and questions in summer 2015. The function for dumpling and loading questions in questionnaires should be re-written:
- There is no session field in questionnaire table now. We do not treat the ordinary rubrics and custom rubric separately. 
- true_false field in questions table is also gone.
- Dumping and loading question should work for all the existing question types.

You should re-write:
- questionnaire_helper.get_questions_from_csv
- questionnaire_helper.create_questionnaire_csv

**Comment by yangsong8** [comment]
Part of E1563

"Test (and fix if they are broken) the export and import functionality. Write test for importing and exporting questionnaires.  "

**Comment by yangsong8** [comment]
1563 was rejected.

**Comment by yangsong8** [comment]
When you work on this, plz make sure you use the import/export controller.

**Comment by efg** [comment]
There are _lots_ of problems here. 

- There's a long header row that mentions fields (e.g., "crypted password") that have nothing to do with rubrics.
- Exported text is not surrounded by quote marks, which means that if there's a comma in a rubric prompt, the comma will be treated as the end of the field.
- There's an "Export Detail" section of the page that (1) doesn't export anything, and (2) gives a list of fields that couldn't relate to a rubric item (e.g., "Score").  Likely these fields belong to responses.  So maybe it should be, "Export responses".

**Comment by efg** [comment]
This is related to E1936, Specialized rubrics, which was merged.

Specialized rubrics are to Review rubrics what role-based reviewing is to Teammate Review rubrics.  So Role-based reviewing should reuse code from specialized rubrics.

**Comment by johnbumgardner** [comment]
closed now that role based reviewing is in Expertiza
