### ISSUE TITLE
Move questionnaire item to arbitrary location

### ISSUE THREAD

**Issue by MikeTheGreat** [expertiza/expertiza#58]
It would be great to be able to insert a new questionnaire item at any place in the existing questionnaire, and to change the order of existing items.

Motivation:
I've got a more detailed explanation of each of the questionnaire items that I'm handing out as part of the homework assignment, and I want the order within the questionnaire to (a) make sense, and (b) match the order of the longer explanations on my website.  

I suppose another nice feature/way to accomplish this would be to allow each item to have a URL for more info, which could then link back to the explanations on my website....

**Comment by yangsong8** [comment]
This feature is provided by the seq. number in questions table.
