### ISSUE TITLE
When a topic is approved & the student is auto-signed up for it, the "Your approved suggested topic" header should be removed.

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#580]
When a student suggests a topic and the instructor approves it, it appears in a table below the other approved topics.  This table is entitled, "Your approved suggested topic."

However, if the student has requested to work on this topic, it instead appears in the main list of approved topics, meaning that there are no table lines under the "Your approved suggested topic" header.  Since there are no entries in the table, the table header should be suppressed.

![image](https://cloud.githubusercontent.com/assets/127445/9750415/84a1e5c4-5665-11e5-9078-0665be9e7d29.png)

**Comment by Winbobob** [comment]
Already been fixed.
