### ISSUE TITLE
When editing an assignment, the name of the assignment should be shown

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#621]
When the Edit Assignment screen is up, it does not say which assignment it is editing.  It would be useful to give the name of the assignment, and in parentheses, the course name, if applicable.

**Comment by yangsong8** [comment]
I become the 1st contributor of Expertiza after this commit. 
![image](https://cloud.githubusercontent.com/assets/4420550/11615172/d0233b6c-9c27-11e5-815b-46669ed5fa3f.png)
