### ISSUE TITLE
A user with a TA account can no longer do assignments as a student

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#647]
When a user's account is changed to a TA account, his/her homepage becomes an instructor's homepage, listing "Courses Assignments Questionnaires" across the top.  The TA should still be able to do an assignment as a student by using the button in the right corner to select "Assignments" from the menu (between "Survey Deployments" and "Course Evaluation"), but if he (xpan in this case) tries that, the following notifier is shown, and the user is taken back to the instructor's homepage:

**This teaching assistant is not allowed to display this eula**

It needs to be fixed so that a TA will see "Assignments" in the top menu bar and be able to do assignments as a student.

xpan is a former TA of mine for another course who is now taking CSC 517.  He is unable to do assignments.  I will change his account back to a student account to fix the problem for now, but the bug needs to be fixed so it doesn't hit anyone else later.

**Comment by yangsong8** [comment]
Sir, I have put "xpan" as a TA in a course and add him as a participant to a newly-created assignment. I tested many things and it seems he can act as an ordinary assignment participant. He can

-  click "Assignment" then see all the assignment he is in
-  click on an assignment
-  select topic
-  create a team, change team name
-  send an invitation to another user, and that user can join his team
-  submit file and hyperlink
-  do peer-review
-  see peer-review grades
