### ISSUE TITLE
Can't Create a team for the course

### ISSUE THREAD

**Issue by nikraina** [expertiza/expertiza#651]
When I Click on Create Team, i get the following error:-
undefined method `max_team_size' for #<Course:0x000000098928b8>.

The error originates from /expertiza/app/views/teams/new.html.erb  line #9
I guess the issue occurs in the production as well.

Thanks!

**Comment by nikraina** [comment]
Hi,
I think i found the bug:-
the bug seems to be in the following code:-
Team Size:<%= select_tag 'team_size', options_for_select(2..@parent.max_team_size), size: 1 %>
The @parent here can belong to Assignment or Course, but the value max_team_size is only applicable for Assignments, so when you try to create a team for Course, it is unable to find anything remotely related to max_team_size for course and hence the code dumps, Please have an if condition check, and handle these cases as required.
Thanks!

**Comment by yangsong8** [comment]
yes I think you find the reason. Please go ahead and fix it in your OSS project. Thanks.
