### ISSUE TITLE
Copying a rubric doesn't copy the advice

### ISSUE THREAD

**Issue by nilbus** [expertiza/expertiza#69]
Ed: I tried to copy a review rubric, and found that it didn't copy the advice, except for the advice for a score of 1.  This should be an easy fix ... can anyone perform it?
 
Oh, also, I'd like to be able to weight a rubric question 0.  Another easy fix, I think ...

**Comment by yangsong8** [comment]
From the current UI, instructor and give weight 0 to some criterion. 

However, the devices are not still not copied when I tried to copy a rubric.

**Comment by yangsong8** [comment]
Fixed the advice copying
