### ISSUE TITLE
Review report is visible to all the users.

### ISSUE THREAD

**Issue by rkyadav-ncsu** [expertiza/expertiza#693]
I tried to impersonate a student on a new tab and then open review report and reviews done by other students. I was taken to the review report (meant for TA/faculty) but current user used is the impersonated student user. Student users should not be able to see the review report or reviews done by other users. Right now, they can do that, if they know the correct URL and parameters.

**Comment by yangsong8** [comment]
Do u mean that I can impersonate a student then type the url like "0.0.0.0:3000/grades/view?id=772" or "0.0.0.0:3000/review_mapping/response_report?id=772"?

**Comment by rkyadav-ncsu** [comment]
Let me write down the steps.
1) Log in as a TA/Instructor
2) Impersonate as a student.
3) Type this url https://expertiza.ncsu.edu/popup/view_review_scores_popup?assignment_id=[assignment_id]&reviewer_id=[reviewer_id]
As a student user, I can provide any reviewer_id and check any reviewer's (who can be different than the current impersonated user_id) response.

**Comment by yangsong8** [comment]
Okay, I see now.
