### ISSUE TITLE
Instructors can make changes to each others' rubric

### ISSUE THREAD

**Issue by yangsong8** [expertiza/expertiza#696]
I impersonated Dr. Ringleb ("sringleb") and I found that she can change Dr. Gehringer's rubric.

**Comment by efg** [comment]
I hope she doesn't!

**Comment by yangsong8** [comment]
According to the discussion on May 13, an instructor can see the public rubric created by other instructors, however, we do not allow the instructor to make changes to the rubric unless the current user is the owner, the TA of the owner or the admins (including super-admins).

**Comment by efg** [comment]
The only change that should be possible to an existing rubric (that has been used to create at least one response) is editing the wording of criteria.  If they want to do anything else, they have to copy the rubric and then edit it.

Also, there is a question about whether a rubric should even be editable after an assignment has finished.  If you can, then in effect, you can "change history."

**Comment by efg** [comment]
Currently, you get a list of all public review rubrics.  If you try to edit one that's not yours, then you get a notifier that you're not allowed to edit it.  But it would obviously be better if the edit icon just didn't appear for rubrics you can't edit.

Also, by default only your rubrics should be shown.  You should have to click a box to "Show public items", which used to be the case for assignments, but now seems to have been removed.

**Comment by Saurabh110** [comment]
Fixed in pull requests #1061
