### ISSUE TITLE
Require institution to be specified when creating a course

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#702]
Historically, we have created courses without specifying the institution.  Now with the data warehouse storing institution for each course, this is undesirable.  The Create Course page needs to be fixed to tell the creator to specify the institution.

**Comment by yangsong8** [comment]
This will require us to add another institution_id to course table.

**Comment by efg** [comment]
Another issue is that there is currently no way to create an institution from the UI.  It needs to be added to institution_controller.rb.

**Comment by yangsong8** [comment]
Sir, institution can be created here:
![image](https://cloud.githubusercontent.com/assets/4420550/18254205/5aaa7a8e-7369-11e6-90fc-7dedc3511a1f.png)

**Comment by efg** [comment]
Note that I made this part of OSS project Purple (UI issues/fixes).

**Comment by ferryxo** [comment]
Need an UI improvement to add a new institution when it's not on the list. see #964
