### ISSUE TITLE
Do we need a "Has topics?" checkbox on the General tab for assignment creation?

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#709]
We used to have a "Has topics?" checkbox on the General tab, but we removed it, because it was possible to have the box checked even if no topics had been created.

This, though, requires the Topics tab to show up on assignment creation/editing even if the assignment does not use topics. This will tend to be confusing to new users.

We need to reconsider this decision.

**Comment by yangsong8** [comment]
The idea will be that we add a "has topics" checkbox in the general tab, but this does not corresponding field in db. Only when that is checked, we will show topics tab.

**Comment by yangsong8** [comment]
The logic should be, the instructor checks the "has_topics" box, then "save", and the "Topics" tab will show up.

**Comment by efg** [comment]
There is now a "Has topics" checkbox.
