### ISSUE TITLE
Instructor can't edit student profiles from participants list

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#714]
When adding participants to an assignment, the instructor sees a list of participants, with "Edit" links for each.  But, the instructor can fill out the page, and then click on the Edit button at the bottom, but nothing changes!  The next time that student's profile is pulled up, it is the same as it was before.

However, if the instructor _impersonates_ the student and then edits "their" profile, there's a Save button at the bottom of the page, and clicking on it does save the changes that were made.

Seems like a DRY problem to me!

**Comment by yangsong8** [comment]
![image](https://cloud.githubusercontent.com/assets/4420550/17352665/8af65f32-5906-11e6-9da6-8d07f1b9c3ae.png)

![image](https://cloud.githubusercontent.com/assets/4420550/17352674/97af600c-5906-11e6-9c6a-e95c6b1f5ad5.png)

![image](https://cloud.githubusercontent.com/assets/4420550/17352684/b0b691ec-5906-11e6-9e15-2c242045778f.png)

![image](https://cloud.githubusercontent.com/assets/4420550/17352687/b859e278-5906-11e6-9c19-bd49853d2666.png)
