### ISSUE TITLE
Account info should be e-mailed to students the first time they are added to an assgt.

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#717]
When students' accounts are created by importing a CSV on the Users page, they receive e-mails with their user-ID and password.  But if an account is created by adding them as participants to an assignment when they don't already have an account, e-mail is not sent.  Students should receive e-mails upon account creation, regardless of how their account is created.

**Comment by yangsong8** [comment]
Part of E1655 in fall 2016, rejected.
