### ISSUE TITLE
Should be able to give feedback when accepting or rejecting topic suggestions

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#718]
As it is, one can give feedback on topics suggested by students only when the instructor wants the topic to be revised, not when (s)he is approving of rejecting it.  Feedback should be possible in any of these cases.

**Comment by efg** [comment]
Project E1827 supposedly fixed this issue, but the fix is suspect: It added a "suggestions" field to some table, and that field seems badly misnamed.  The instructor can indeed give feedback on a suggestion, but we don't see how that feedback can be viewed by a student.

**Comment by Saurabh110** [comment]
Feedback (comment) can be added before accepting or rejecting any suggestion. The student can view status and comments of/on their topic by clicking on the view link in front of the topic on the suggestions page.
