### ISSUE TITLE
Integrate Simicheck to detect plagiarism

### ISSUE THREAD

**Issue by ferryxo** [expertiza/expertiza#722]
Simicheck is a web service to detect similarity among files. We would like to integrate it into expertiza to check similarity among the submissions. This requires the code to convert submissions (links to google docs, words, etc) to pdf or text files and send them to Simicheck. This needs to be done as a delayed task (several hours after the deadline has passed), store the similarity report in the database, and create a UI to show the report.

**Comment by yangsong8** [comment]
E1692 of Fall 2016

**Comment by yangsong8** [comment]
E1738 in Spring 2017, merged.
