### ISSUE TITLE
Alternate view seems incorrect ...

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#732]
Are the reviews shown in the correct columns in the alternate view?  My review for Round 2 in Wikipedia contribution_Team32 on assignment 783 (Wikipedia contribution) seems to have been written by someone else.  Also, while one can sort the first-round reviews by criteria, it's not possible to sort the second-round reviews!

**Comment by efg** [comment]
The alternate view seems to have been fixed; going to that assignment now does not display the wrong reviewer's name.  However, the sorting issue remains, and will be posted as #963.

**Comment by yangsong8** [comment]
The layout of the heat grid of the 1st and 2nd round review should be the same, however, in both students' and instructors' view, they are different in

- Sortability on criterion and avg column
-  The metric-1 column: it only shows in round-1

![image](https://user-images.githubusercontent.com/4420550/26891327-a331b424-4b82-11e7-991e-32617336d3cd.png)

![image](https://user-images.githubusercontent.com/4420550/26891362-bef62104-4b82-11e7-8894-18ae8d0651b7.png)
