### ISSUE TITLE
Add past-due assignments to the task list

### ISSUE THREAD

**Issue by nilbus** [expertiza/expertiza#80]
The task list shows students upcoming assignments, but they don't see anything that is past due. This makes it so that the work is less likely to be done.

Mike Roda: "After studying the new task list code that was integrated, I have come to the conclusion that significant changes would be required to show late tasks. The current design identifies tasks by the stage deadline, and the view expects any tasks identified to correspond to the current stage.  To support late tasks, the code would probably need to be redesigned."

**Comment by efg** [comment]
This is a long-standing issue, and we have specified projects to fix it once or twice.  But the implementations have been messy and I liked the system the way it was before, better than after this feature was added.  I don't think that it is at all necessary, so we should make this issue the lowest possible priority.

**Comment by efg** [comment]
Fixed, by Project E2110, which was merged.
