### ISSUE TITLE
Link topics to their description on Google Docs

### ISSUE THREAD

**Issue by ferryxo** [expertiza/expertiza#829]
Currently, the students / instructor can only see the titles of the topics, and they have to go to google docs to see the complete write up. The problem is the link to the google docs is not shown anywhere in expertiza (usually it's in moodle). Sometimes the students are even not aware of the google doc. 

We should link those topics to the topics in the google doc. the header in the google docs must be bookmarked so that they have unique links that can be referenced from Expertiza.

**Comment by yangsong8** [comment]
This functionality has been provided by E1697 which has been merged. We are using this now in Expertiza:
![image](https://cloud.githubusercontent.com/assets/4420550/23758556/2f452fc0-04b8-11e7-925f-e535b2627b15.png)
