### ISSUE TITLE
Team names created by bidding are incorrect

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#842]
Somewhere in the bidding code, or the code that assigns topics based on bids, team names are generated.  In this case, team names are not appended to the name of the assignment, like they are when teams are created elsewhere in the code.  I am not sure that they even use the same sequence counter.  Some of the team names that have the assignment name prepended are very high, e.g., 759, suggesting that something in the algorithm creates a lot of unneeded or unused teams (thereby bloating the db).

**Comment by Saurabh110** [comment]
Team names are created using 'create_team_and_node' in teams.rb which seems normal flow of execution.
