### ISSUE TITLE
Lack of clear licensing

### ISSUE THREAD

**Issue by spotrh** [expertiza/expertiza#843]
This code base is missing clear licensing. The only indication of the license that I could find was in bower.json, which says "MIT". Please consider taking the following actions:

- Adding information to README.md which describes the licensing for expertiza (and any third party components which are bundled in)
- Adding a COPYING file which includes the actual MIT license text (and any other licensing texts that third party components bundled in have)
- Adding per-file license attribution. Files are often copied out of projects and used in other places, without this, the licensing of those files gets lost. This can be as simple as a header comment which says:
`/* foo.rb is a part of the expertiza project, which is licensed MIT. See COPYING for details. */`

- Normally, the same header would be the appropriate place to put a copyright statement, but its not clear to me who exactly holds copyright here (it looks like the answer might be a "lot of people"). I strongly suggest creating an AUTHORS file and putting names in there, then amending the per-file header to something like:
`/* foo.rb is part of the expertiza project: https://github.com/expertiza/expertiza */`
`/* Copyright (c) 2016. For a list of copyright holders, see AUTHORS */`
`/* The license of this work is MIT. See COPYING for details. */`

**Comment by Winbobob** [comment]
Thank you very much for your advise, @spotrh!
I just added the MIT license, see e96e442788306e27ae8689ad2acd7dd042d05a57.
