### ISSUE TITLE
Cc: instructor on e-mail to students

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#87]
It's sometimes very difficult for an instructor to see if Expertiza is e-mailing students when it should.  It would be very helpful to have a profile attribute for an instructor to get a copy of all e-mails (or certain kinds of e-mails) sent to students.

**Comment by yangsong8** [comment]
Part of E1655 in fall 2016, rejected.

**Comment by efg** [comment]
Related to #111, which should be included in the same project.

**Comment by johnbumgardner** [comment]
Tag is there in profile. Unable to edit it. Some problem in the form. 

Also, we are not ever using this user preference when sending emails.
