### ISSUE TITLE
Authlogic is not used fully in Expertiza

### ISSUE THREAD

**Issue by nilbus** [expertiza/expertiza#90]
A group of CSC517 students added Authlogic for authentication. However, the implementation was incomplete. We had to create our own [modified authlogic gem](https://github.com/expertiza/authlogic) to make it work with our database schema, so there's potentially high upkeep cost here. For what little Authlogic is doing for us right now, it almost doesn't make sense to have it. However, it does gain us some benefits. We just need to finish the job.
### What was implemented:
- The User model `acts_as_authentic`, which means we don't have to do our own crypto, salting, and password checking. It also gives us password and other validations.
- `current_user` and `current_user_session` methods were added to ApplicationController, but they are not used anywhere. Everything still relies on `session[:user]`, which is still being set by Goldberg in `vendor/plugins/goldberg_filters/lib/goldberg_filters.rb`.
### What needs to be done:
- Replace `session[:user]` references with `current_user`
- Ensure logging in and out in AuthController creates and destroys the SessionUser, rather than mucking with `session[:user]`
- Ensure that all the tests still pass

And whoever looks into this, please look at this at a higher level and be sure that doing this actually makes sense. Is there any point to this? If it's not making the code simpler and easier to understand, then this should be reconsidered.

**Comment by efg** [comment]
No longer relevant.
