### ISSUE TITLE
Adding a nonexistent user to a team causes traceback

### ISSUE THREAD

**Issue by gtungatkar** [expertiza/expertiza#91]
When, from the instructor interface, one creates a team and then attempts to add a user that does not exist (e.g., mistypes the username), the following error occurs:

NoMethodError in Teams usersController#create

undefined method `master_permission_granted' for nil:NilClass

RAILS_ROOT: /local/rails/expertiza/releases/20110820160528
Application Trace | Framework Trace | Full Trace

app/models/assignment_team.rb:192:in `add_participant'
app/models/team.rb:60:in`add_member'
app/controllers/teams_users_controller.rb:27:in `create'

/usr/local/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/base.rb:1253:in `send'
/usr/local/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/base.rb:1253:in`perform_action_without_filters'
/usr/local/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/filters.rb:617:in `call_filters'
/usr/local/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/filters.rb:610:in`perform_action_without_benchmark'
/usr/local/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/benchmarking.rb:68:in `perform_action_without_rescue'

**Comment by efg** [comment]
Verified as still extant.

**Comment by efg** [comment]
Still extant.
