### ISSUE TITLE
Import of topics chokes on special characters

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#918]
I tried to import a list of topics together with the descriptions.  It seems that non-ASCII characters in the description (e.g., a curly apostrophe, and perhaps also an en-dash) caused a SQL error in inserting the description string into the db.  I had to edit the import file to remove non-ASCII characters.  Any Unicode character ought to be allowed in a description.

**Comment by yangsong8** [comment]
We are going to migrate the db to postgresql during the summer. Will revisit this issue after that.

**Comment by nikolaygtitov** [comment]
For curly apostrophe in the descriptions (to get a curly apostrophe I had to use Word and copy paste that character), it resulted in the following error: ArgumentError in ImportFileController#import:
invalid byte sequence in UTF-8

**Comment by Saurabh110** [comment]
Fixed in 20edb13974f4fb0744d487d04eae396693cc8ba0
