### ISSUE TITLE
Contributor name changes when teammate views author feedback

### ISSUE THREAD

**Issue by gtungatkar** [expertiza/expertiza#92]
The bug that was preventing teammates from seeing author feedback submitted by other team members has apparently been fixed.  That's the good news.

The bad news is that after the teammate views or edits the author feedback, the Contributor name at the top of the page changes to the name of the teammate who originally entered the author feedback.

This really doesn't hurt anything, but it is potentially confusing.  In all other circumstances, View Scores pulls up a header line with the logged-in student's name, not their partner's.

**Comment by efg** [comment]
This is also related to #622
