### ISSUE TITLE
Trying to impersonate someone you can't impersonate returns an error

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#928]
If I try to switch from impersonating one student to another, and the student I am trying to impersonate was not created by me, the system is supposed to disallow the impersonation.  It does, but it gives a cryptic error message, something about "[]".  It should say, "You cannot impersonate <username>",  That's what it tells me if I am logged in as myself and pull down the **Manage > Impersonate user** menu.  It should do that even when I am impersonating someone else.

**Comment by ferryxo** [comment]
it seems to have been fixed by an OSS project in spring'17
