### ISSUE TITLE
Refactor E1735 and remove useless partials, still have 2 issues

### ISSUE THREAD

**Issue by Winbobob** [expertiza/expertiza#953]
1. On student-end, Expertiza use `grades/_reviews.html.erb` partial to display reviewers, scores and review details; on instructor-end, since Expertiza uses a tabbed view, so `grades/_reviews.html.erb` is separated into two. One is `grades/tabbed_reviews` (display review details) in `Reviews` tab. Another one is `grades/_team_statistics.html.erb` (display reviewers and scores) in `Statistics` tab. We need to use same kinds of partials in instructor-end and student-end.
2. `Give Feedback` link at `view_my_score` at student-end should not appear at folded view. The link should appear at the bottom of expanded view.

(See 0bf0aa55d8db679ae26e05ae241e4e25ad26f2e5)

**Comment by yangsong8** [comment]
E1735 might be the cause of #958
