### ISSUE TITLE
The review report does not show scores assigned correctly

### ISSUE THREAD

**Issue by yangsong8** [expertiza/expertiza#958]
Below is a screenshot from assignment 834's review report.

![image](https://cloud.githubusercontent.com/assets/4420550/26256975/c76b2f1e-3c8c-11e7-8fb3-83db72bc3947.png)

This student did 4 reviews, but it does not show the scores assigned by the reviewer.

**Comment by efg** [comment]
This seems to work for old assignments.  Maybe it just doesn't work if the assignment has rubrics that vary by round.

**Comment by efg** [comment]
This bug has reappeared.  When fixed, it should also be checked on staggered-deadline assignments, e.g., "Madeup problem" (assgt. 843), because they have been buggier than other assignments in this regard.

**Comment by efg** [comment]
Yes, it works for assignments that only have one round of review, but not for those with two rounds of review.  Not sure what would happen if there were two rounds that used the same rubric.
