### ISSUE TITLE
HTML tags appearing in review text need to be escaped

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#962]
In my review of a paper for WCAE 2017, I included several "-->" (arrows) in the review text, indicating that I wanted the authors to modify wording in their paper.  However, it turns out that "-->" closes an HTML comment, and this caused the text from my review to show up at the end of the previous review, as well as in my review, where it belonged.

The solution would be to escape any text string in a comment that could be interpreted as an HTML tag.

**Comment by yangsong8** [comment]
This might be a fix we can try:
https://stackoverflow.com/questions/4052906/how-to-display-content-with-raw-html

**Comment by ferryxo** [comment]
This happens in the score heatmap

**Comment by efg** [comment]
This problem no longer occurs.
