### ISSUE TITLE
When creating a course, should there be an "Add institution" option?

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#964]
When a course is created, the first field is the institution.  However, if the institution doesn't exist, an admin(!) needs to go to the Administration -> Show -> Institutions menu, which is way too complicated.  Instead, there should be an option at the bottom of the combo box that says, Add Institution.

However, it might be better to have the admin create the institution when (s)he creates the instructor account.  That way, we don't get duplicates, e.g., "North Carolina State University" and "NC State University".

**Comment by nikolaygtitov** [comment]
When a course is created, the institution field is given in the form of dropdown box with limited list.
As an instructor, it is not clear how to add new institution using the UI (not the link) For this matter, see #987 issue (since it is related).

**Comment by efg** [comment]
The admin can _attempt_ to create a new institution when creating a new instructor.  But, after one types in the name of the institution & clicks create, it crashes.  

This _appears_ to be because there is no code to assign Instructor as the role (even though the Roll dropdown is pre-scrolled to show "Instructor").
