### ISSUE TITLE
Number of reviews allowed and required need to be stated coherently

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#969]
The Review Strategy tab includes options, "Set Allowed Number of Reviews per reviewer" and "Set Required Number of Reviews per reviewer."  Not only is the capitalization all wrong, but there is nothing that explains the difference between allowed and required reviews.  Moreover, when a student tries to do a review, the page says, e.g.,

Number of Reviews Allowed: "3"
You are required to do 3 reviews

The syntax is different, the punctuation is wrong, I believe that the line might even appear if the number of allowed or required reviews is not set on the Review Strategy tab, and again, there's no explanation of the difference between the two.  Better would be,

"You may perform between 3 and 3 reviews" , or, when the number of allowed & required reviews are the same, "You should perform exactly 3 reviews."
Or, "Your instructor expects you to do 3 reviews, and you are not allowed to do any extra reviews."

**Comment by efg** [comment]
Was part of E1777, which we (still) plan to merge.

**Comment by nikolaygtitov** [comment]
Per student's view it is a little more complex:

You should perform exactly 3 reviews
You are required to do 3 reviews
Number of reviews left: 3

All these three lines could be rephrased as suggested.
Per instructor's point of view there still the following options in the "Review Strategy" tab:

Set allowed number of reviews per reviewer
Set required number of reviews per reviewer

Thus, E1777 still was not merged to take effect on these changes.
