### ISSUE TITLE
private URL parameter gets lost after validation errors when creating an assignment

### ISSUE THREAD

**Issue by nilbus** [expertiza/expertiza#97]
Steps to reproduce:
1. As an instructor or admin, click to create a public or private assignment. Note the private=X in the URL
2. Click create without filling in any duedates. It will redirect back to the same page with a validation error related to the duedates
3. Fill in duedates and click create
   
   Mysql::Error: Column 'private' cannot be null: INSERT INTO `assignments` (`name`, `review_of_review_questionnaire_id`, `review_topic_threshold`, `created_at`, `num_reviews`, `num_review_of_reviewers`, `staggered_deadline`, `updated_at`, `directory_path`, `submitter_count`, `private`, `teammate_review_questionnaire_id`, `team_assignment`, `num_review_of_reviews`, `reviews_visible_to_all`, `spec_location`, `allow_suggestions`, `wiki_type_id`, `max_reviews_per_submission`, `team_count`, `course_id`, `instructor_id`, `require_signup`, `author_feedback_questionnaire_id`, `review_questionnaire_id`, `num_reviewers`, `days_between_submissions`, `review_assignment_strategy`) VALUES('private', NULL, 0, '2011-09-11 02:56:11', 0, 0, 0, '2011-09-11 02:56:11', '', 0, NULL, NULL, 0, 0, 0, '', 0, 1, NULL, 0, NULL, 2, NULL, NULL, NULL, 0, 0, 'Instructor-Selected')
   
   expertiza/app/controllers/assignment_controller.rb:108:in `create'

To resolve this issue, a hidden field could be added named private which gets its value from params[:private], which will be present whether it comes from the URL params or the hidden field. Alternatively, since there's already a hidden field sending that value, maybe it should populate itself from params[:assignment][:private] instead of params[:private].

**Comment by efg** [comment]
This _can't_ still be extant, after the assignment controller was rewritten in 2014 and no one has reported the bug since.
