### ISSUE TITLE
Dynamic assignment of metareviews does not work

### ISSUE THREAD

**Issue by yangsong8** [expertiza/expertiza#970]
I impersonated a student in assignment 658, then clicked the "Request a new metareview to perform" and got an error message.
![image](https://user-images.githubusercontent.com/4420550/27145251-0c9abc82-5103-11e7-9432-e38bc6028526.png)

**Comment by ferryxo** [comment]
Was the "include?" method previously there?

**Comment by efg** [comment]
This should have been fixed when E1774 was merged, or even before that, by Zhewei, but I just tried it on the CHEP demo assignment, and that assignment doesn't work at all.  This needs to be checked with a working assignment.
