### ISSUE TITLE
When edit an assignment, changing the number of review rounds doesn't work

### ISSUE THREAD

**Issue by ferryxo** [expertiza/expertiza#972]
Using the code on Github (June 14, 2017), the button to update the number of review rounds doesn't work. It throws Uncaught TypeError: due_dates_table_element_list[i].id.split(...).last is not a function

**Comment by ferryxo** [comment]
also, the 2 popups (confirm before changing and after changing the rounds) are not necessary. 1 is good.

**Comment by efg** [comment]
This has been fixed.
