### ISSUE TITLE
There is no way to change the role of a user anymore ...

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#973]
The project that implemented clicking on a student's ID to impersonate that student was merged incorrectly.

It used to be that clicking on a student's ID in the users list allowed one to edit the student's profile.  But now, clicking on that ID impersonates the student.  There is no link to edit the student.  According to the project specs, clicking on a student's _name_  is supposed to edit the profile, but it doesn't.  It needs to.

Suppose you want to make a student a TA.  You can try clicking on the student's role (that is clickable).  But if you try, the system tells you you can't edit it.  This needs to be fixed too.

**Comment by yangsong8** [comment]
Fixed.
