### ISSUE TITLE
When someone impersonates a user, then reverts, he often ends up as admin ...

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#981]
... instead of the user (s)he impersonated.

This is a security hole, since potentially any user can become admin.

**Comment by Winbobob** [comment]
I think it may because the last session is not clean completely. If you try to manually test in the private browser tab, it should work fine.

**Comment by nikolaygtitov** [comment]
This is definitely bug. I logged in as instructor. Then impersonated a student and used "revert" option. It reverts me to admin. Thus, any instructor may become admin.

**Comment by Saurabh110** [comment]
Could not reproduce.
