### ISSUE TITLE
The institution list should be sorted alphabetically

### ISSUE THREAD

**Issue by yangsong8** [expertiza/expertiza#987]

**Comment by efg** [comment]
And, how do you navigate to the institution list?  I can get there by typing in the URL, but there has to be another way.

This is not only a problem in the Institution list, but also in the Institution dropdown when creating a new course.

**Comment by efg** [comment]
Administration > Show > Institutions (!)

**Comment by efg** [comment]
Lo and behold, the institution list **is** sorted alphabetically if you get to it from Administration > Show > Instructors  ... New Instructor.  But not if you get to it from where you assign a course to an institution.
