### ISSUE TITLE
User experience improvements for the Docker development environment

### ISSUE THREAD

**Issue by nilbus** [expertiza/expertiza#993]
@Winbobob, I see you have set up a [Docker environment for expertiza development][existing], which is a great idea—Docker offers a straightforward, cross-platform way to start from a working base image, like the VCL, but with persistence (gems, DB, etc.) and with the ability to edit and commit locally. I like that you added this as an option on the project Readme. I think that it could be possible for us to streamline the Docker development experience enough that it becomes the preferred solution, above VCL and local development, both of which have their frustrating drawbacks.

[existing]: https://hub.docker.com/r/winbobob/expertiza-fall2016/
[Readme]: https://github.com/expertiza/expertiza/blob/master/README.md#ncsu-vcl-image

I recently contributed to [exercism.io][]'s docker development setup and think that it provides an excellent example that Expertiza developers could benefit from following. Like Expertiza, Exercism has a fairly large number of contributors that aren't experienced with Rails and its development ecosystem. The exercism.io [getting started with Docker devbox documentation][docs] is pretty well-geared toward beginners unfamiliar with Docker/Rails and could be used as a source of inspiration for your own.

[exercism.io]: http://exercism.io/
[docs]: https://github.com/exercism/exercism.io/tree/master/docker

The major differences from what I understand of your current approach with Docker:
- The database's persistent data is stored in a named volume attached to a separate Postgres container, so the expertiza app container can be updated/recreated without having to start the database from scratch.
- docker-compose is used to simplify the commands the user must run to start the container, i.e. `docker-compose up` instead of `docker run --expose 3000 -p 3000:3000 -v /home/expertiza-developer:/home/expertiza-developer/expertiza -it winbobob/expertiza-fall2016`.
- The image build is extensible and reproducible using a Dockerfile, rather than created with `docker commit`.
- A setup script automates the [Config Expertiza][config] steps that must be run on each container.

[config]: https://hub.docker.com/r/winbobob/expertiza-fall2016/

The process for someone getting started looks about like this:

### Initial setup

- Install Docker and git
- Fork and clone the expertiza repository
- `docker-compose build` — downloads the base image, and incrementally updates gems if there are local Gemfile changes
- `docker-compose run app bin/setup` — create this `bin/setup` script to seed/migrate the development database, starting from an export stored in your own database image built FROM postgres

### Development session

- `docker-compose up` — brings up the database and rails application, bound to a local port

---

At a high level, this works by adding a `Dockerfile` ([example][Dockerfile]) and `docker-compose.yml` ([example][compose]) to your project's root. These specify how to build the development environment, which will require you to codify the steps you used to build your existing image. Register the project with Docker Hub as a new Automated Build ([instructions][hub]). Each time the project's master branch is updated, Docker Hub will automatically build a new public image. docker-compose builds a `Dockerfile.dev` ([example][dev]) image based on the last-pulled public `expertiza/expertiza` base image from the Docker Hub.

See the [developer documentation][docs] for the nitty-gritty instructions on how an end-user would set up this environment, specific to Exercism.

[Dockerfile]: https://github.com/exercism/exercism.io/blob/master/Dockerfile
[compose]: https://github.com/exercism/exercism.io/blob/master/docker-compose.yml
[dev]: https://github.com/exercism/exercism.io/blob/master/Dockerfile.dev
[hub]: https://github.com/exercism/exercism.io/pull/3593#issue-244233355

---

What do you think of this approach? Did the students using the existing image run into any challenges that you think this approach and the accompanying documentation might help address? Feel free to ask me anything about it. If you like the idea, I would be happy to help guide your efforts.

/cc @yangsong8 @efg

**Comment by Winbobob** [comment]
Hi @nilbus,

Thank you very much for your valuable suggestions. I think they are great ideas.
Actually, some suggestions you mentioned have already in my TODO list
1. I will definitely create a setup script including install all dependencies and additional software/libraries.
2. Use `docker-compose` to detach DB to a separate docker image and use local `Dockerfile` to achieve extensible and reproducible docker image build.
---
The most-used method for students to setup the environment is the `.ova` file we offered to students. It is cumbersome but easy.
Also, I cleaned the `sessions` table and the size of current DB is less than 120 MB. I am planning to create a scrubbed lightweight DB instead of asking students to dump the whole Expertiza DB each time.

Regards,
Zhewei

/cc @efg  @yangsong8 @nilbus

**Comment by nilbus** [comment]
Nice. Keep up the good work. :thumbsup:

**Comment by Winbobob** [comment]
Hi @nilbus,

Docker-compose is online now. 😄  (00b4540e48a975f7885bf51695770d49cced7f23)

Regards,
Zhewei
/cc @efg @yangsong8

**Comment by nilbus** [comment]
Cool, way to go! It looks like even though the database is scrubbed, you want to keep it somewhat protected (not available on docker hub)?

**Comment by Winbobob** [comment]
Hi @nilbus, I did not commit scrubbed db to docker hub. And [this docker image](https://hub.docker.com/r/winbobob/expertiza/) is the rails environment for Expertiza. Yeah, I stored the scrubbed db in Google drive and shared to students.

Do you have better ideas about storing db? One way I can think about is not use scrubbed at all and using `seed.rb` to populate the db.

**Comment by Winbobob** [comment]
We created [docker-compose file](https://github.com/expertiza/expertiza/blob/master/docker-compose.yml.example), [elaborated tutorial and corresponding shell scripts](https://github.com/expertiza/expertiza/tree/master/docker).
