### ISSUE TITLE
Old teams appear in "View submissions" for current assignment

### ISSUE THREAD

**Issue by efg** [expertiza/expertiza#994]
When submissions are viewed for OSS/Writing Assignment 2 in Spring 2017, several teams show up that are composed of students from the Fall 2016 course.  These teams have not submitted anything, but they still show up in the listing.

One hypothesis is that the teams were created by the bidding algorithm, and all their members subsequently left for other teams.  But that still doesn't explain why (i) the team was not deleted when its last member left, and (ii) why students from a _previous_ semester were members of the team.

**Comment by Winbobob** [comment]
(i) the team was not deleted when its last member left
In each team, there are still some members. So those teams were not deleted.
(ii) why students from a previous semester were members of the team.
I am not sure why this happened. I have already deleted these teams and participants. If this situation happens again, I will look into it.

**Comment by Saurabh110** [comment]
Could not reproduce.
