### ISSUE TITLE
The login form does not verify captcha when captcha is shown

### ISSUE THREAD

**Issue by chyiz** [expertiza/expertiza#997]
Tested on production expertiza.

Steps to reproduce:
Try to login with an invalid username and password.
The captcha appears.
Ignore the captcha and put in a valid username and password, and try to submit.

Expected result:
Login failed with error message asking user to finish captcha.

Actual result:
Login successful, but the "Wrong password" error message is still shown .

**Comment by ferryxo** [comment]
I wasn't able to reproduce this in my dev machine. 
it shows "Please do reCAPTCHA before trying to login again."

Unless you changed the username, then you don't need to do recaptcha for the 1st time. 
Recaptcha is needed when several login attempts are done for the same username. This is done so to avoid brute force attack.

**Comment by chyiz** [comment]
No I didn't change username when I tried the said steps.
The behavior definitely changed from when I opened this issue. Now I can't get captcha to show up at all on production.
